### ISSUE TITLE
[newPlatform] [browserSide] Migrate Security

### ISSUE THREAD

**Issue by sortiz1191** [wazuh/wazuh-dashboard-plugins#2701]
Parent issue | https://github.com/wazuh/wazuh-kibana-app/issues/2660
------------ | -------------
Branch | [feature/2701-migrating-plugin-browser-side-security](https://github.com/wazuh/wazuh-kibana-app/tree/feature/2701-migrating-plugin-browser-side-security)

### Description
Migrate security

### Tasks
- [x] Creating route for /security using React router at /public/app-router.tsx
- [x] Create security subroutes for users, policies, roles and role-mapping
- [x] Import Users component for Security tab
- [x] Import Roles component for Security tab
- [x] Import Policies component for Security tab
- [x] Import Roles mapping component for Security tab

**Comment by sortizowlh** [comment]
-> Solve import problems from these files:
- public/components/common/hooks/use-index-pattern.ts
- public/components/common/hooks/use-filter-manager.ts
- public/components/common/hooks/use-time-filter.ts

-> Add useHistory component for react router
-> Add useLocation component for check current URL and select current tab at security

**Comment by Desvelao** [comment]
This section was migrated to use the ReactJS router as part of this pull request: https://github.com/wazuh/wazuh-dashboard-plugins/pull/6689.

So this issue can be closed.
