### ISSUE TITLE
Improve overall perceived performance

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-dashboard-plugins#4155]
## Project's description

Our users' feedback tells us the perceived performance of the applications is too slow. Through this issue, we want to centralize all the works we want to do to improve the perceived performance. 

We're going to analyze the application behavior in a canonical environment, built based on the previous research by the @wazuh/qa in https://github.com/wazuh/wazuh-qa/issues/2766 and in our recommended settings [documentation](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/index.html).

We need to prioritize our most commonly used dashboards and widgets first. All the pages, widgets, etc. reviewer must appear on this issue. Please update it and link the correspondent issues on where this is being worked on.

* Wazuh health check
* Wazuh -> Modules -> Security Events -> Dashboard
...

## Project's milestones

- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4351
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/4366
- [ ] Create the canonical environment using terraform or other automation means
- [ ] Generate data and load to simulate a moderately loaded environment
- [x] Measure the perceived performance, setting a baseline
  - [x] Identify tools to measure the time from each user action to the returned feedback
  - [ ] Identify slow widgets, events, queries and visualizations
  - [ ] Propose, develop and test fixes for each issue found
- [x]  Measure the perceived performance after the fix, reporting the improvement from the baseline

## Particular issues

- [x] #3812
- [x] #3623
- [x] #4388
- [x] #4314
- [ ] #4029 
- [x] #4105 
- [x] #5233

**Comment by AlexRuiz7** [comment]
## Status review - 08 Aug 2022

- #3812 @asteriscos is migrating the generation of reports to the backend (includes the queries to Elastic). Might need additional changes, if so, the issue will be moved to `blocked` until these changes are completed.
- #4366 @Mayons95 and @mauceballos. Great progress so far, but the sub-issues (PRs) need extended information, describing **what** was included, **why** and **how that helps** us in this project. In particular, I'd like to see the results of these scripts, the results, either as PDF or images, so anyone visiting this project can quickly see its utility. See https://github.com/wazuh/wazuh-kibana-app/pull/4371#pullrequestreview-1060248368
- [New issue] Revisit the required fields of wazuh-monitoring, and optimize the cron job accordingly

**Comment by AlexRuiz7** [comment]
## Status review - 29 Aug 2022

We need a test environment with heavy load to measure the impact of the changes made. As a result, we'll prioritize the creating of this environment.

After that, we will measure the impact of #3812, and then start with #3626.

**Comment by gdiazlo** [comment]
I'm closing this, we will open a new effort in the future, tied to other app refactors.
