### ISSUE TITLE
[Update dashboards] Global vulnerabilities dashboards

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-dashboard-plugins#5763]
## Introduction

With the new vulnerability detector work (https://github.com/wazuh/wazuh/issues/14153), we can start implementing a global vulnerability dashboard which can manage all detected vulnerabilities across all endpoints.

We will implement this dashboard under Modules / Vulnerabilities: 

![image](https://github.com/wazuh/wazuh-kibana-app/assets/2181918/137a9520-ec4f-45b8-9f7d-fbe17411fb6b)

without selecting an agent, this page will show the default dashboard, which will be designed like the following mock:

![image](https://github.com/wazuh/wazuh-kibana-app/assets/2181918/3067dcdd-cd43-4065-a995-6fe6a0b9211b)

We won't be using the embedded Discover to implement the inventory or the vulnerabilities table, instead, we will use a standard table component with an expand action, which will display a fly-out with the details about the vulnerability selected. This design will take advantage of the new vulnerabilities index schema to ensure all vulnerabilities contain a minimum set of information required by our users.

The single agent dashboard will use the global one with an agent filter applied.

## Development plan

In order to create the new vulnerabilities dashboard we need to define different tasks/steps:

- **Research stage**
  - [x] wazuh/wazuh-kibana-app#5800
  - [x] wazuh/wazuh-kibana-app#5839
  
- **Components and services**
  - [x] #5945
    - Known issue solved: https://github.com/wazuh/wazuh-kibana-app/issues/5969
  - [x] #5946
  
- **Demo stage**
  - [x] #5894
  - [x] #5895

- **Improve and fixes stage**
  - [x] #6064

  
> - Create visualization definitions using the OSD Visualize plugin (2.9.0) and the new vulnerabilities index pattern.
> - Use the dashboard plugin react component to render the vis definitions created in the previous step
> - Add a searchbar component to filter the events
> - Repeat the process for the dashboard and inventory tabs
  
- **Test and documentation stage**
  - [x] Add unit test, e2e testing, etc.
  - [x] Add documentation to reuse in other module dashboards

### We want to implement a new `dashboard` tab:

- [x] Vulnerabilities search bar
  - We must use the platform search bar component
  - We must search in the new vulnerability index
  - Each time we search, all the dashboard must update to reflect the results based on the search bar filter
- [x] ~~Cross search vulnerability with alerts~~
  - ~~Investigate how can we cross-search the vulnerability index with the general alerts index to search for additional information from within the vulnerability dashboard~~ (It's not possible cross-search the vulnerability index with the general alerts index)
- [x] Filter by vulnerable product
  - A user must be able to quickly select a product from a list and add it as a filter to the search bar
- [x] Filter by operating system version
  -  A user must be able to quickly select an OS version from a list and add it as a filter to the search bar
- [x] Easy filter by agent group
  -  A user must be able to quickly select an endpoint group from a list and add it as a filter to the search bar
- [x] ~~cves by severity~~ 
  - ~~A user must be able to quickly see the amount of CVEs by severity: critical, high, medium, low~~ (There is not enough information in the index to make a graph like this. Replaced with Accumulation of the most detected vulnerabilities)
- [x] open vs closed vulnerabilities over time
  - A user must be able to quickly see the tendency of open vs closes vulnerabilities. This information comes from the alerts index, instead of the vulnerabilities one, so this graph must have its own time filter
- [x] top 10s graphs
  - A user must be able to see 
    - the most detected vulnerabilities
    - the most vulnerable endpoints
    - ...
- [x] vulnerabilities table
   - sort by values like the vulnerability score
   - ~~actions:~~
     - ~~See details on a fly out ~~(It's not possible)
     - ~~Go to alerts index with a filter by that vulnerability~~ (It's not possible)
- [x] ~~evaluate the performance of the dashboard in scenarios with thousands of endpoints~~ (does not apply to this issue)
- [x] ~~Reporting~~ (this functionality will be implemented later)
  - ~~A user should be able to export the query results~~
  - ~~A user should be able to create a report out of the dashboard~~

We might need to implement new configuration options to support the new vulnerability detector under the current configuration module.

- [x] New vulnerability detector configuration options

### We want to implement a new `inventory` tab:

- [x] Add related native searchbar
- [x] New inventory table using native indexer table (as is possible)
- [x] Add filters and columns switcher 

## Dependencies

This work depends on the vulnerability index schema and a set of sample data to build the queries to generate and test the dashboard visualizations and queries.

## Related issues

We will add here issues from our backlog and projects related to this effort.

**Comment by sempervictus** [comment]
Reporting and export of query results for this dashboard might get interesting based on the proposed composition. Suggest adding it as a first tier specification to avoid complications formatting those down the line.
Thanks for picking this up folks.

**Comment by chantal-kelm** [comment]
Based on the details of the topic, we elaborated the following dasboards, we will continue to work on their appearance and on the data to be displayed.

<img width="1792" alt="Captura de pantalla 2023-09-19 a la(s) 14 31 16" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/ad80fd12-4764-4720-8ac1-1dcf04a5c432">
<img width="1792" alt="Captura de pantalla 2023-09-19 a la(s) 14 27 16" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/91bede13-9572-4dcb-8da1-13e042c43c54">

**Comment by chantal-kelm** [comment]
Update dashboard

<img width="1792" alt="Captura de pantalla 2023-09-20 a la(s) 13 56 42" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/5a676009-b01d-4e38-9993-65bb007b6257">
<img width="1792" alt="Captura de pantalla 2023-09-20 a la(s) 13 57 10" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/393ac6cb-5c6f-4d73-a81e-a59af8670555">
<img width="1792" alt="Captura de pantalla 2023-09-20 a la(s) 13 57 01" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/f604f9de-4416-41bd-aedb-386b97f46926">

**Comment by micsinyei** [comment]
I am very interested in this dashboard, how do you show the active vulnerabilities since the current filtering does not allow that?

Can you provide some information on it?

**Comment by botkillern** [comment]
> Creation of the `wazuh-states-vulnerabilities` index

I think the comment from @jbiset is about it. (Creation of the `wazuh-states-vulnerabilities` index)
You need to create a new index just for vulnerabilities...

Anyway, still in development.

I'm very interested in this feature too.

**Comment by Machi3mfl** [comment]
@botkillern and @micsinyei, thanks for your feedback. 
That's right, @botkillern. This is only for development purposes.

**Comment by Machi3mfl** [comment]
## Vulnerabilities inventory

<img width="721" alt="Screenshot 2023-10-31 at 15 55 39" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/ba32bc8c-f3f2-4ad5-aeff-c634851e344d">
<img width="1437" alt="Screenshot 2023-10-31 at 15 56 18" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/cf1900a8-d9e2-441f-a8a3-a76f11023756">
<img width="1438" alt="Screenshot 2023-10-31 at 15 57 13" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/14de07f0-06c4-44ff-97b7-7cfa0485da60">

**Comment by ygeorgiev** [comment]
do you have ETA?

**Comment by Dretreyt** [comment]
> Update dashboard
> 
> <img alt="Captura de pantalla 2023-09-20 a la(s) 13 56 42" width="1792" src="https://private-user-images.githubusercontent.com/99441266/269363096-5a676009-b01d-4e38-9993-65bb007b6257.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MDE4MTMsIm5iZiI6MTcwODYwMTUxMywicGF0aCI6Ii85OTQ0MTI2Ni8yNjkzNjMwOTYtNWE2NzYwMDktYjAxZC00ZTM4LTk5OTMtNjViYjAwN2I2MjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDExMzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MTBkNGRlMDI4ODU5MTMzNDFiYzhiM2RmOGNjODJjM2U2YWIzOGViZmY5MDYwZmZmYjE0N2UxYWI2MmIzODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4RsrVMADcKkuaklEX_diD-XIuL6CxnQLwRGLtf4j9dI"> <img alt="Captura de pantalla 2023-09-20 a la(s) 13 57 10" width="1792" src="https://private-user-images.githubusercontent.com/99441266/269363073-393ac6cb-5c6f-4d73-a81e-a59af8670555.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MDE4MTMsIm5iZiI6MTcwODYwMTUxMywicGF0aCI6Ii85OTQ0MTI2Ni8yNjkzNjMwNzMtMzkzYWM2Y2ItNWM2Zi00ZDczLWE4MWUtYTU5YWY4NjcwNTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDExMzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMGI3NmNlMmRiYjM1ZDk1Mzk2M2UzODAyZjkyNTJlMTlkYjk4N2EyYzBiZTBmZGUwNzNjNDJjN2UyNjA1NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vrl9Jgs4Ru4vOqwmu93UixQfHFwQX1PAk-DenWmYJ8U"> <img alt="Captura de pantalla 2023-09-20 a la(s) 13 57 01" width="1792" src="https://private-user-images.githubusercontent.com/99441266/269363089-f604f9de-4416-41bd-aedb-386b97f46926.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MDE4MTMsIm5iZiI6MTcwODYwMTUxMywicGF0aCI6Ii85OTQ0MTI2Ni8yNjkzNjMwODktZjYwNGY5ZGUtNDQxNi00MWJkLWFlZGItMzg2Yjk3ZjQ2OTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDExMzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiMTg3MmM2MDI1YTk0MGEzNGYwMWIxY2FiNzJmNjJkZjBlNzE2NGU0NDc3NmQyZTIzODRjZWZkOTYyZmUxMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NPGunJ-j5tGom23f-FNuSxj18jgFEov7gAjqlWDMbsI">

Hi,

Have you got the guides on setting up these visualizations please?

Thanks

Rob

**Comment by Jarli01** [comment]
Yeah this would be amazing if released, having a default overview of all vulnerabilities out of the gate would simply make the tool useful. 

Individual results, while useful is annoying to have to go back and forth between.

**Comment by burdorff** [comment]
If I'm reading all the details here correctly, this is in process for Wazuh 4.8 and is present in the current beta.  It appears that the primary delay was the need for a new indexer/index to keep track of the vulnerabilities that are "current" instead of listing both active and solved as the Events table does.

**Comment by Jarli01** [comment]
@burdorff correct, the need to generate a new indexer appears to be the hold up.

**Comment by mesutgungor** [comment]
Mean Time To Detect MTTD and Mean Time to Fix MTTF are the two crucial KPIs to put this dashboard I think.
