### ISSUE TITLE
Update dashboards

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-dashboard-plugins#5818]
# Description

Following the release of our integrations' documentation, we want to incorporate the new dashboards into our main application.

## Functional requirements

- Users must be able to visualize and interact with the new dashboards
- Users must be able to interact with the search bar and get dashboard contents updated
- Users must be able to interact with the time selector of a visualization and all visualization of the dashboard must update with the new selection
- Users without the appropriate roles should not be able to view a dashboard

## Non-functional requirements

- All dashboards must update to changes of the search bar
- All dashboards must have matching colors for the same information
- All dashboards must have limited the amount of information they can display, so there is no overflow of legends or lines
- All titles and texts must use the i18n framework if possible
- All queries must take into account the size of the information they are going to display, to limit the max amount of information when it makes sense, in order to preserve the responsiveness of the dashboard
- All queries must be documented in the dashboard implementation guide

## Implementation restrictions

- Update the dashboards' implementation guide
- Use built-in styles and components 
- We must clean the current design, introducing the appropriate guards and tests to ensure the correct rendering even if the available data is not correct

## Plan

- [x] Create dashboards definitions
  - [x] wazuh/wazuh-kibana-app#5838
  - [x] wazuh/wazuh-kibana-app#5898
  - [x] wazuh/wazuh-kibana-app#5909
  - [x] wazuh/wazuh-kibana-app#5911
  - [x] https://github.com/wazuh/wazuh-kibana-app/issues/5763
    https://documentation.wazuh.com/4.3/_images/screenshot-05-Wazuh-Vulnerability-Detection1.png
  - [x] wazuh/wazuh-kibana-app#5930
  - [x] wazuh/wazuh-kibana-app#5933
  - [x] wazuh/wazuh-kibana-app#5938
  - [x] wazuh/wazuh-kibana-app#5940
  - [x] wazuh/wazuh-kibana-app#5941
 - [x] Update dashboards implementation with the new definitions
 - [x] wazuh/wazuh-dashboard-plugins#6066
 - [x] wazuh/wazuh-kibana-app#6071
 - [x] wazuh/wazuh-kibana-app#6074
 - [x] wazuh/wazuh-kibana-app#6079
 - [ ] ~~After implementing the dashboard log data analysis in our plugin, we will have to develop a flyout when clicking on the data in the table.~~
 - [ ] ~~After implementing the dashboard integrity monitoring in our plugin, we will have to develop a flyout when clicking on the data in the table.~~
 - [x] Add the necessary changes to make easier the dashboard customization
- [x] Add all the related visualizations to the dashboard (to see and decide which visualizations will be added to the definitive dashboard)
- [x] Create a update dashboard guide to use in the next dashboards updates

**Comment by Machi3mfl** [comment]
# Research

- Research about implementation cost on dashboard upgrade (In progress ⏳)

**Comment by chantal-kelm** [comment]
| Category | Name | ID | Section in monolith plugin | Changes | Design | New dashboard
|---|---|---|---|---|---|---|
| Endpoint security | Security Configuration Assessment | security-configuration-assessment | Modules > Security Configuration Assessment | RENAME Configuration assessment | [Design](https://documentation.wazuh.com/4.3/_images/screenshot-06-Wazuh-Configuration-Assessment1.png) | New dashboard in progress |
| Endpoint security | Policy monitoring | policy-monitoring | Modules > Policy monitoring | RENAME to Malware detection  (this is rootcheck now) | [Design](https://github.com/wazuh/wazuh-kibana-app/issues/5898#issuecomment-1724589591) | [New dashboard](https://github.com/wazuh/wazuh-kibana-app/assets/99441266/5d8ae850-6be6-4116-96f1-4f8b4f34f483) |
| Endpoint security | Integrity monitoring | integrity-monitoring | Modules > Integrity monitoring | RENAME to File integrity monitoring | [Design](https://documentation.wazuh.com/4.3/_images/screenshot-04-Wazuh-File-Integrity-Monitoring1.png) |  [New dashboard](https://github.com/wazuh/wazuh-kibana-app/assets/99441266/4f8ef322-60d1-4470-bc23-d8e192727304) |
| Endpoint security | System auditing | system-auditing | Modules > System auditing | DELETE | | |
| Endpoint security | OpenSCAP | openscap | Modules > OpenSCAP | DELETE | | |
| Endpoint security | CIS-CAT | ciscat | Modules > CIS-CAT | DELETE | | |
| Threat intelligence | Security events | security-events | Modules > Security events | RENAME Threat hunting | [Design](https://github.com/wazuh/wazuh-kibana-app/assets/6089438/a4aef55d-3038-4fa4-adb8-cb71b4558c68) | [New dashboard](https://github.com/wazuh/wazuh-kibana-app/assets/99441266/b7ec13f7-ba94-4293-a163-fb1c02c6261e) |
| Threat intelligence | Vulnerabilities | vulnerabilities | Modules > Vulnerabilities | RENAME to Vulnerability detection | | [New dashboard](https://github.com/wazuh/wazuh-kibana-app/assets/99441266/f604f9de-4416-41bd-aedb-386b97f46926) |
| Threat intelligence | MITRE ATT&CK | mitre-attack | Modules > MITRE ATT&CK | | | |
| Threat intelligence | Virustotal | virustotal | Modules > Virustotal | | | |
| Security operations | PCI DSS | pci-dss | Modules > PCI DSS | | [Design](https://documentation.wazuh.com/4.3/_images/screenshot-08-Wazuh-Regulatory-Compliance1.png) | [New dashboard](https://github.com/wazuh/wazuh-kibana-app/assets/99441266/65c69181-0510-4306-9a37-4d302624968e) |
| Security operations | GDPR | gdpr | Modules > GDPR | |
| Security operations | HIPAA | hipaa | Modules > HIPAA | |
| Security operations | NIST 800-53 | nist-800-53 | Modules > NIST 800-53 | |
| Security operations | TSC | tsc | Modules > TSC | |
| Security operations | IT Hygiene | it-hygiene | Agents > {agent_id} -> Inventory |  |
| Security operations | Osquery | osquery | Modules > Osquery | DELETE |
| Cloud security | AWS | amazon-web-services | Modules > AWS | | [Design](https://documentation.wazuh.com/4.3/_images/screenshot-09-Wazuh-Cloud-Security1.png) | [New dashboard](https://github.com/wazuh/wazuh-kibana-app/assets/99441266/f4ca5b69-b3d7-4dbb-83fb-a0bddf7e0abb) |
| Cloud security | Google Cloud | google-cloud | Modules > Google Cloud | |
| Cloud security | GitHub | github | Modules > GitHub | |
| Cloud security | Office365 | office365 | Modules > Office365 | |
| Cloud security | Docker listener | docker-listener | Modules > Docker listener | RENAME to Docker | [Design](https://documentation.wazuh.com/4.3/_images/screenshot-10-Wazuh-Containers-Security1.png) | [New dashboard](https://github.com/wazuh/wazuh-kibana-app/assets/99441266/c34e1e14-14c9-466d-9515-35990566a921) |
