### ISSUE TITLE
Register the new applications

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-dashboard-plugins#5841]
As part of the work to move the current menu to the platform menu.

We must register the new applications in the platform menu:

| Category | Name | ID | Section in monolith plugin |
|---------------------|-----------------------------------|---|---------------------------------------------|
| Endpoint security | Overview | wz-home | Modules directory |
| Endpoint security | Endpoints summary | endpoints-summary | Agents |
| Endpoint security | Integrity monitoring | integrity-monitoring | Modules > Integrity monitoring |
| Endpoint security | Policy monitoring | policy-monitoring | Modules > Policy monitoring |
| Endpoint security | Security Configuration Assessment | security-configuration-assessment | Modules > Security Configuration Assessment |
| Endpoint security | System auditing | system-auditing | Modules > System auditing |
| Endpoint security | OpenSCAP | openscap | Modules > OpenSCAP |
| Endpoint security | CIS-CAT | ciscat | Modules > CIS-CAT |
| Thread intelligence | Security events | security-events | Modules > Security events |
| Thread intelligence | Vulnerabilities | vulnerabilities | Modules > Vulnerabilities |
| Thread intelligence | MITRE ATT&CK | mitre-attack | Modules > MITRE ATT&CK |
| Thread intelligence | Virustotal | virustotal | Modules > Virustotal |
| Security operations | PCI DSS | pci-dss | Modules > PCI DSS |
| Security operations | GDPR | gdpr | Modules > GDPR |
| Security operations | HIPAA | hipaa | Modules > HIPAA |
| Security operations | NIST 800-53 | nist-800-53 | Modules > NIST 800-53 |
| Security operations | TSC | tsc | Modules > TSC |
| Security operations | IT Hygiene | it-hygiene | Agents > {agent_id} |
| Security operations | Osquery | osquery | Modules > Osquery |
| Cloud security | AWS | amazon-web-services | Modules > AWS |
| Cloud security | Google Cloud | google-cloud | Modules > Google Cloud |
| Cloud security | GitHub | github | Modules > GitHub |
| Cloud security | Office365 | office365 | Modules > Office365 |
| Cloud security | Docker listener | docker-listener | Modules > Docker listener |
| Server management | Rules | rules | Management > Rules |
| Server management | Decoders | decoders | Management > Decoders |
| Server management | CDB lists | cdb-lists | Management > CDB lists |
| Server management | Groups | groups | Management > Groups |
| Server management | Status | server-status | Management > Status |
| Server management | Cluster | cluster | Management > Cluster |
| Server management | Statistics | statistics | Management > Statistics |
| Server management | Logs | logs | Management > Logs |
| Server management | Reporting | reporting | Management > Reporting |
| Server management | Settings | settings | Management > Configuration |
| Server management | API console | api-console | Tools > API console |
| Server management | Ruleset test | ruleset-test | Tools > Ruleset test |
| Server management | RBAC | rbac | Security |
| Management | Server API | server-api | Settings > API configuration |
| Management | Modules | modules | Settings > Modules |
| Management | Server data | server-data | Settings > Sample data |
| Management | Configuration | configuration | Settings > Configuration |
| Management | Logs | app-logs | Settings > Logs |
| Management | About | about | Settings > About |

# Tasks
- [x] Add new applications to the global menu
- [x] Redirect to the particular view when accessing to the application from the side menu
- [x] Remove `wazuh` application
- [x] Create service to generate the redirections
- [x] Remove unwanted navigation by tabs

**Comment by Desvelao** [comment]
# Meeting

- Discuss the names for Amazon AWS and Google Cloud applications names
