### ISSUE TITLE
Share state between applications

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-dashboard-plugins#5849]
**Description**
The sections of the current plugin will be moved to applications and we need them to share some states:

- Selected agent
- Selected group

Switching applications causes the page to be refreshed, and it causes some side effects as the Redux store or some singleton are recreated, losing the previous data. Depending on the section, this could not be managed and cause unexpected behavior.

The shared states or selections are done through data stored:
- Redux store
- shareAgent singleton (agent and group)
- URL parameter

Avoiding that the data store is reset, would simplify status sharing.

## Tasks
- [x] Ensure the selected agent is kept while switching the applications
- [x] Ensure the selected group is kept while switching the applications
- [x] Research and remove as possible the refresh of the page due to certain conditions when the application is mounted
- [x] Research the rest of the refresh page

**Comment by Desvelao** [comment]
# Research

The selected agent data is stored in the Redux store.

Due to a problem related to the application being refreshed when it is mounted, the Redux store is reset. This causes the data of the selected agent to be lost. Some sections are trusting in this store to manage the view.

We added a workaround to this problem. When the agent data is updated in the store, the data will be saved in the sessionStore. If the page is refreshed, the Redux store, will use the stored data in the sessionStore to recreate it. In this way, the data of the selected agent will be kept in page refreshes.

Related commit: https://github.com/wazuh/wazuh-kibana-app/commit/0c4ab1ac5b7f732811cde40d0e2ae63ab55d8052

**Comment by Desvelao** [comment]
# Research

I have researched about the page being refreshed under certain conditions when the Wazuh applications are mounted. This causes the stores to be reset and switching applications is slower it should be.

The following commit https://github.com/wazuh/wazuh-kibana-app/commit/e7699a5b307bcf1a4144af00d59fecca7af2b7c8, added a new condition to the page is refreshed when the application is mounted. This fix solved a problem related to the `ScopedHistory` when switching applications to the Wazuh plugin.

Now, as the Wazuh plugin will be separated into different applications and the intention is to keep some shared states, this solution causes the stores to be reset, losing the previous data. So we must remove the page as refreshed as possible, or else we should recreate the state taking in account the previous state.

If the page is not refreshed when switching from Discover application to some of Wazuh, then the following error is displayed:
```
Error: ScopedHistory instance has fell out of navigation scope for basePath: /app/discover
    at ScopedHistory.verifyActive (scoped_history.ts:246:1)
    at ScopedHistory.listen (scoped_history.ts:132:1)
    at angular_config.tsx:76:1
    at Object.invoke (angular.js:5208:1)
    at angular.js:5007:1
    at forEach (angular.js:388:1)
    at createInjector (angular.js:5007:1)
    at doBootstrap (angular.js:1963:1)
    at Object.bootstrap (angular.js:1984:1)
    at mountWazuhApp (application.ts:18:1)
```

## Digging

The problem seems to be related to the `app/discover` AngularJS module.

The current Wazuh plugins contain a stripped Discover application. This is defined through an Angular module. So the Wazuh plugin defines an AngularJS module called `app/discover` with the requirements to work within the Wazuh application.

For another hand, the Discover application defines the `app/discover` Angular JS module.

Depending on the navigation, the `app/discover` AngularJS module could be replaced.

### Switching application flow
When the application is stated for the first time, it defines an `app/discover` AngularJS module. If the page is not refreshed, this module definition will be kept.

If the user navigates to the Discover application through the side menu, only for the first time it is accessed, it will define the `app/discover` module, replacing the existent `app/discover` module that could be defined by the Wazuh application.

After that, both applications, Wazuh and Discover initiated the inner AngularJS. Switching to the Wazuh application causes the bootstrap, which uses the `app/discover` AngularJS module defined by the Discover application. This module and its runBlocks/configBlocks are causing the error related to ScopedHistory.

The current fix to this behavior was refreshing the page, which causes the AngularJS modules to be cleared, so the Wazuh plugin can define and use the `app/discover` module that works.

A solution to this problem is to rename the `app/discover` AngularJS module defined by the Wazuh plugin. This will do when the Wazuh application is bootstrapped, and uses the module defined by Wazuh instead of `app/discover` AngularJS module that could have been defined by the Discover plugin. Renaming it, seems to solve the problem, but there are more AngularJS modules that have name conflicts between the Wazuh and Discover plugins. These name conflicts could cause other problems. The ideal solution would be to rename all the AngularJS modules that the Wazuh plugin is defining and are defined by the Discover plugin too.

**Comment by Desvelao** [comment]
We have decided to keep the page refreshed when one of the applications is mounted.

**Comment by yenienserrano** [comment]
The selected api is being lost every time the plugin is changed. It always reverts to the first active api of wazuh.yml.

<details><summary>Details</summary>

```xml
hosts:
  - manager:
      url: 'https://wazuh.manager'
      port: 55000
      username: wazuh-wui
      password: MyS3cr37P450r.*-
      run_as: false
  - imposter:
      url: 'http://imposter'
      port: 8080
      username: wazuh-wui
      password: MyS3cr37P450r.*-
      run_as: false
  - imposter-cli:
      url: 'http://192.168.64.110'
      port: 8088
      username: wazuh-wui
      password: MyS3cr37P450r.*-
      run_as: false
```
Manager: not active
Imposter: active
Imposter-cli: active

![image](https://github.com/wazuh/wazuh-kibana-app/assets/63758389/1f6424ae-7174-45fd-b54b-f9c2677ca5d1)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/63758389/2faa11d0-a00c-418e-bba6-48e3c8088ee5)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/63758389/7980cdfe-6d46-42ae-94e6-8cd74e1d29a8)
</details>

**Comment by yenienserrano** [comment]
It seems to be saved by application

<details><summary>Details</summary>
<p>

![image](https://github.com/wazuh/wazuh-kibana-app/assets/63758389/393723cb-c511-4941-991e-2662e1f5b00e)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/63758389/146b4312-aa72-4930-99ec-b12f34df749a)


</p>
</details>

**Comment by yenienserrano** [comment]
When a filter is pinned and the plugin is changed, the filter disappears.

<details><summary>Details</summary>
<p>

![image](https://github.com/wazuh/wazuh-kibana-app/assets/63758389/fb66c524-0b57-4e55-bf21-d0ddebb12320)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/63758389/4b56916f-2e84-416d-ae79-1bf22d9305c9)

</p>
</details>
