### ISSUE TITLE
[Vulnerabilities dashboard] Replace the `Inventory` tab using OSD plugins

### ISSUE THREAD

**Issue by Machi3mfl** [wazuh/wazuh-dashboard-plugins#5895]
## Description

Replace the Inventory tab using OSD plugins (Dashboard/Embeddables/Visualizations Builder) - More details below-

### Check 2.10.0 discover design

![Screenshot 2023-10-03 at 12 03 33](https://github.com/wazuh/wazuh-kibana-app/assets/6089438/6dfe7b85-00b2-4937-bd80-27c0348461d8)

Components
- Searchbar
- Sidebar with fields selector (Example: src/plugins/data_explorer/public/components/sidebar/index.tsx)

```tsx
<EuiPageSideBar />
```
- Table with details flyout (Example: src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx)

```tsx
<EuiDataGrid />
<EuiFlyout />
```

### Opensearch UI 1.3.0

- https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/package.json#L128C31-L128C31
- https://oui.opensearch.org/1.3/#/

## Tasks

- [x] Create the inventory tab considering to use native OUI components
- [x] Use the search bar service created
- [x] Add a search bar component to filter the events

**Comment by Machi3mfl** [comment]
# New inventory tab

## New features

- DataGrid 
- Flyout with document details
- Index pattern search

![Screenshot 2023-10-20 at 10 29 58](https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/2f2105c3-6128-4d73-8916-b60405512a18)

![Screenshot 2023-10-20 at 10 30 15](https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/e809b24d-0950-419d-91bc-287ffd9a4af6)

**Comment by Machi3mfl** [comment]
https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/a80df033-665c-438c-87da-c47fd5b411a4

**Comment by Machi3mfl** [comment]
# New vulnerabilities inventory

# Search bar

### The search bar connected to the new vulnerabilities index

<img width="1510" alt="Screenshot 2023-10-24 at 15 34 07" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/bbbaeec6-9247-4e09-92fe-c2ca76e123a8">

# Data Grid

<img width="1510" alt="Screenshot 2023-10-24 at 15 32 52" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/a7c7f954-510d-490f-9b3f-b10250f6b45d">

The data grid component has the following features:


- Table columns selector to switch the table columns visibility

<details>

<img width="1511" alt="Screenshot 2023-10-24 at 15 35 33" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/574873db-1ff2-44f7-992c-10187d868dca">

</details>

- Column sorter, adds the possibility to sort by all the columns

<details>

<img width="450" alt="Screenshot 2023-10-24 at 15 36 49" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/ca4f18cc-b02b-4ad4-b518-901e6cfba8b5">

</details>


- Pagination and rows per page selector 

<details>

<img width="1505" alt="Screenshot 2023-10-24 at 15 40 03" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/7340e94a-4497-442b-b8c3-995c4aee52db">

<details>


- Document details by clicking on the table row

<details>

<img width="1511" alt="Screenshot 2023-10-24 at 15 42 10" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/ad4f0e47-7278-40d9-a3d4-97f566f161d1">

<details>


https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/0e2f12b4-dcee-4dd8-9b13-c2d583da78d4

**Comment by Machi3mfl** [comment]
## Considerations

When the index pattern has a wrong template the order and hide/show columns will be shown fields with type keyword.
These types make a wrong behavior when we try to order by these fields or shown in the table.

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/66cadc6c-f96b-4e78-9056-d48ab66350cd)

To fix it it's important to create the index and mappings correctly following these steps: https://github.com/wazuh/wazuh-dashboard-plugins/pull/5966#issue-1919982504

Then, the keyboard fields will disappear from the column select and will be sorted correctly by all the index fields.


https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/7eb30f09-936f-4e5f-a24f-52a3005f1ee8
