### ISSUE TITLE
[Update dashboards] Update `security configuration assessment` dashboard

### ISSUE THREAD

**Issue by chantal-kelm** [wazuh/wazuh-dashboard-plugins#5930]
## Description

Update the security configuration assessment dashboard.

## Dashboard Mock

![image](https://documentation.wazuh.com/4.3/_images/screenshot-06-Wazuh-Configuration-Assessment1.png)

**The dashboard mock serves as a design prototype (the information shown is only an example)**

## Tasks

- [x] Add tab called dashboard
- [x] Make the default information displayed be that of the first policy in the table
- [x] Create definition for table display
- [ ] ~~Add search bar and time filter to table~~
- [x] Make graphics update when another policy is chosen
- [x] When accessing from the agent welcome show the information of the selected policy in the agent welcome
- [x] Update the graphs when another agent is selected in both the inventory tab and the dashboard tab.
- [x] Allow to select an agent in the new dashboard tab
- [ ] ~~Update colors to create a consistent color palette~~ -> [After some research, the following conclusion was reached](https://github.com/wazuh/wazuh-kibana-app/issues/5838#issuecomment-1707163985)
- [ ] wazuh/wazuh-dashboard-plugins#6059
- [ ] ~~Document the differences between `wazuh-kibana-app` and `integrations` dashboard (information shown)~~ -> [comment](https://github.com/wazuh/wazuh-kibana-app/issues/5898#issuecomment-1724589591)

**Comment by chantal-kelm** [comment]
Since this dashboard is a design we have to see how we adapt and implement it.

Initial proposal: 

As soon as we enter the Inventory tab we should show only the table we currently have with all the policies and remove the donut.
This is the image of what we currently have:

![image (5)](https://github.com/wazuh/wazuh-kibana-app/assets/99441266/5f2cc0c4-79f6-484c-9703-e3b623b03949)

After clicking on a policy in that table, we take it to the dashboard that we were asked to create, which would be this one:

![image (6)](https://github.com/wazuh/wazuh-kibana-app/assets/99441266/d07f8302-6d51-4797-897a-0766351f0324)

The first table of the dashboard we already have it only that currently when you click on a policy the detail opens downwards and in the image of the dashboard that we were asked to create it opens to the side. We would have to make it open to the side.

The donut that is requested in the new dashboard seems to be a donut over all the policies, in this case we are going to make it show the data only of the previously selected policy.

**Comment by chantal-kelm** [comment]
**First screen:**

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/e39248a5-f2e7-4250-bd78-d7bd0560b56d">

**Second screen:**

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/2ab802f9-0115-4405-930b-60ee8790bf14">

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/688f3e1c-9098-449d-9631-ac675d7f0814">

**Comment by chantal-kelm** [comment]
In a meeting today with @gdiazlo it was decided to organise the dashboard differently.

**Comment by chantal-kelm** [comment]
<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/66f90e4f-7f1f-4ef9-bf67-3033c488f256">

**Comment by chantal-kelm** [comment]
<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/495ad15f-b34b-4f03-9ca9-f1c1ebbe790a">

**Comment by chantal-kelm** [comment]
<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/96f1bb43-b633-451f-acb5-ba46346a027a">

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/d38271e0-7888-44ab-a44d-2a7262341be8">

**Comment by chantal-kelm** [comment]
It was decided to make a refactoring in the section to solve technical debt errors that we have been carrying for a long time.
