### ISSUE TITLE
Remove the visibility configuration of modules and define and implement the ability to visualize applications

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-dashboard-plugins#5965]
**Description**
As part of the development of the global menu, the visibility of the Wazuh modules will be deprecated and the main application will be removed and split into multiple applications.

## Tasks
- [x] Remove the visibility of Wazuh modules
  - [x] Remove the view to configure the modules in the UI
  - [x] Remove settings related to configuring the visibility of modules on the configuration file, ability to configure from UI
  - [x] Remove the persistence of visibility of modules ( `wazuh-registry.json`)
- [x] Remove the setting `disabled_roles` related to the visibility of the main application on the configuration file and UI.
- [x] Remove the logic related to extensions
- [x] Add a migration to remove the  `extensions` key in the host data stored in `wazuh-registry.json`
- [x] Update the documentation

**Comment by JuanGarriuz** [comment]
To update documentation we have to change some images:

- source/user-manual/capabilities/file-integrity/use-cases/detecting-malware-persistence-technique.rst - line 54
- source/user-manual/capabilities/agentless-monitoring/use-cases.rst - line 67, 158
