### ISSUE TITLE
Support new stage RC 3 for 4.5.3 in wazuh-kibana-app repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard-plugins#5971]
## Description

This issue attempts to support a new stage RC 3 for 4.5.3 in the wazuh-kibana-app repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.3 (if applicable).
- [x] Bump revision for branch 4.5.3 on wazuh-kibana-app repository.
  - https://github.com/wazuh/wazuh-dashboard-plugins/pull/5973
  - https://github.com/wazuh/wazuh-dashboard-plugins/pull/5974
  - https://github.com/wazuh/wazuh-dashboard-plugins/pull/5975
- [x] Create tag v4.5.3-rc3 from branch 4.5.3 on wazuh-kibana-app repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard-plugins/releases/tag/v4.5.3-2.6.0-rc3.
