### ISSUE TITLE
Support new stage RC 1 for 4.6.0 in wazuh-dashboard-plugins repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard-plugins#5978]
## Description

This issue attempts to support a new stage RC 1 for 4.6.0 in the wazuh-dashboard-plugins repository.

## Tasks

- [x] Ensure changelog is updated for 4.6.0 (if applicable).
- [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/5979
- [x] Create tag v4.6.0-rc1 from branch 4.6.0 on wazuh-dashboard-plugins repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard-plugins/releases/tag/v4.6.0-2.8.0-rc1
