### ISSUE TITLE
Support new stage Alpha 1 for 4.7.0 in wazuh-dashboard-plugins repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard-plugins#6002]
## Description

This issue attempts to support a new stage Alpha 1 for 4.7.0 in the wazuh-dashboard-plugins repository.

## Tasks

- [x] Ensure changelog is updated for 4.7.0 (if applicable).
- [x] Bump revision for branch 4.7.0 on wazuh-dashboard-plugins repository.
- [x] Create tag v4.7.0-alpha1 from branch 4.7.0 on wazuh-dashboard-plugins repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard-plugins/releases/tag/v4.7.0-alpha1.
