### ISSUE TITLE
Support new Wazuh version 4.5.4 in wazuh-dashboard-plugins repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard-plugins#6008]
## Description

This issue attempts to support a new version 4.5.4 in the wazuh-dashboard-plugins repository.

## Tasks

- [x] Create numbered branch for version (4.5.4) using branch 4.5.4 on wazuh-dashboard-plugins repository.
- [x] Bump 4.5.4 branch to 4.5.4 version on wazuh-dashboard-plugins repository, including revision and changelog.
  - [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6010
  - [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6011
  - [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6013
