### ISSUE TITLE
Support new stage Alpha 1 for 4.5.4 in wazuh-dashboard-plugins repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard-plugins#6024]
## Description

This issue attempts to support a new stage Alpha 1 for 4.5.4 in the wazuh-dashboard-plugins repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.4 (if applicable).
- [x] Bump revision for branch 4.5.4 on wazuh-dashboard-plugins repository.
  - [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6025
  - [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6026
  - [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6027
- [x] Create tag v4.5.4-alpha1 from branch 4.5.4 on wazuh-dashboard-plugins repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard-plugins/releases/tag/v4.5.4-2.6.0-alpha1.
