### ISSUE TITLE
Post release tasks for 4.5.4

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard-plugins#6044]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.5.4.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.5.4-into-4.6.0`.

## Tasks

- [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6049
- [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6050
- [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6051
- [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6052
- [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6053
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.5.4 (https://github.com/wazuh/wazuh-dashboard-plugins/releases).
- [x] Delete all stage tags for v4.5.4. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.5.4-rc1, 4.5.4-alpha1, etc.
- [x] Delete branch `4.5.4`.
- [x] Update [Compatibility Matrix](https://github.com/wazuh/wazuh-dashboard-plugins/wiki/Compatibility) in the repository wiki.
