### ISSUE TITLE
Post release tasks for 4.6.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard-plugins#6078]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.6.0.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.6.0-into-4.7.0`.

## Tasks

- [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6081
- [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6082
- [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6084
- [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6085
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.6.0 (https://github.com/wazuh/wazuh-dashboard-plugins/releases).
- [x] Delete all stage tags for v4.6.0. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.6.0-rc1, 4.6.0-alpha1, etc.
- [x] Delete branch `4.6.0`.
- [x] ~~Update [Compatibility Matrix](https://github.com/wazuh/wazuh-dashboard-plugins/wiki/Compatibility) in the repository wiki.~~ This is not required as from this version Wazuh will no longer support Kibana
