### ISSUE TITLE
Support new stage Alpha 2 for 4.7.0 in wazuh-dashboard-plugins repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard-plugins#6089]
## Description

This issue attempts to support a new stage Alpha 2 for 4.7.0 in the wazuh-dashboard-plugins repository.

## Tasks

- [ ] Ensure changelog is updated for 4.7.0 (if applicable).
- [ ] Bump revision for branch 4.7.0 on wazuh-dashboard-plugins repository.
- [ ] Create tag v4.7.0-alpha2 from branch 4.7.0 on wazuh-dashboard-plugins repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard-plugins/releases/tag/v4.7.0-alpha2.
