### ISSUE TITLE
Adapt and enhance the releasing tools for the unique platform

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-dashboard-plugins#6091]
## Description
Starting with 4.6.0 release, the Wazuh plugin is not released for Kibana versions, so we must adapt the releasing tools to the unique platform (Wazuh dashboard).

## Tasks

- [x] Create tag and bump scripts in the root that manages the task for the repository instead of the specific `plugins/main`
- [x] Support to bump the `package.json` and `opensearch_dashboards.json` manifest files for each plugin.
- [x] Add the ability to run specific bump tasks for each plugin
  - [x] `plugins/main` must run the task to update the API data information from the API spec URL file
