### ISSUE TITLE
Refactor Inventory and, FIM dashboards

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6133]
## Description

We need to replace the Inventory, File Integrity Monitoring, and Security Configuration Assessment dashboards which are part of the global queries objective.

The refactoring of the Vulnerability detector dashboard was the first step toward the global indexer queries goal, thus we want to use the same strategies to refactor SCA, FIM, and Inventory. This will allow us to design new use cases and enhance the existing ones.

## Functional requirements

- The user must be able to search and use all the current features in each of the apps.

## Non-functional requirements

- None of the current features should be lost.
- The FIM and SCA apps must have Dashboard, Inventory, and Events tabs. 
- The endpoint Inventory app must only have a Dashboard and Inventory tab.
- We should validate during the health-check process that each index pattern exists.

## Implementation restrictions

- Avoid using AngularJS.
- We must re-use the same components developed in the Vulnerabilities detector app.

## Plan

- [x] Analyse current dashboards and present a design proposal for each one
- [ ] Refactor File Integrity Monitoring
  - [x] Create FIM visualizations
  - [x] #6178 
  - [x] Refactor FIM inventory tab
  - [x] Refactor FIM events tab
- [ ] Refactor Endpoint Inventory
  - [ ] Create Endpoint Inventory visualizations
  - [ ] Create Endpoint Inventory dashboard 
  - [ ] Create Endpoint Inventory dashboard tab
  - [ ] Create Endpoint Inventory inventory tab
- [ ] Refactor Security Configuration Assessment

## UPDATE

This Objective has been postponed for a future release.

**Comment by chantal-kelm** [comment]
We started by analysing the current dashboards to see what we want to keep in what we currently offer and what we want to add or change, and based on that, present a design proposal.

**Comment by chantal-kelm** [comment]
Working on the proposed design of the FIM dashboard, 2 proposals for improvement were identified, which are: 

*Add 4 metrics at the top of the dashboard, which can provide a quick overview of data and numbers.

*Do not repeat more than one type of graph on a dashboard in order to attract the user's attention and make them stay more on the page, because if there is a donut type graph and a foot type graph on the same dashboard, visually they are very similar, and can overwhelm the reading of the graphs for the user.

**This is our current FIM dashboard without a pineado agent.**

![image (16)](https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/1dd783af-e064-4728-b947-8f547b9a78c7)

**This is our current FIM dashboard with pinned agent, I think that in this case I would also add the 4 metrics in this case of the selected agent.**

![image (18)](https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/9a717102-149b-4969-be2c-470fe913fe33)

**FIM dashboard with pineado agent with the 4 metrics**

![image (17)](https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/5ae78739-4a8f-4ddd-969c-8a8150dcb0e9)

**Implementing the two points mentioned above:**

![image (20)](https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/6f8ec41e-0585-40fa-91e6-de21d7203b52)
![image (21)](https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/842b3c73-ff03-4370-bef7-22c2fe5bb595)
![image (22)](https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/c7fdd511-7fff-4190-a0e5-6e20d128fa1f)

**Comment by chantal-kelm** [comment]
According to what we discussed today with @asteriscos about the proposal of the FIM dashboard with pineado agent, the design has been modified, I share the image with the last changes.

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/a7b14cb3-aacc-457f-973a-f2e3ce5a3171">

**Comment by asteriscos** [comment]
## Update
This Objective has been postponed for a future release.
