### ISSUE TITLE
Create unique Agents preview React component

### ISSUE THREAD

**Issue by lucianogorza** [wazuh/wazuh-dashboard-plugins#6150]
|Part of Epic|
|---|
|#6129|
## Description
This issue is intended to replace the rendering of several agent preview components with a single React component on the angular template context.

## Tasks

- [x] Create unique Agents preview React component
- [x] Use the new component in the angular template
- [x] Remove evolution chart
- [x] Make `Register Agent` component accesible from a new url
- [x] Create a new component to show when there are no registered agents instead of directly redirect to register agent.
- [x] Restructure files and folders components
