### ISSUE TITLE
Post release tasks for 4.7.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard-plugins#6152]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.7.0.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.7.0-into-4.7.1`.

## Tasks

- [x] Merge branch `4.7.0` into branch `4.7.1`. Already synced by the previous sync task. No PR was created.
- [x] Merge branch `4.7.1` into branch `4.8.0`. https://github.com/wazuh/wazuh-dashboard-plugins/pull/6158
- [x] Merge branch `4.8.0` into branch `4.8.1`. https://github.com/wazuh/wazuh-dashboard-plugins/pull/6159
- [x] Merge branch `4.8.1` into branch `master`. https://github.com/wazuh/wazuh-dashboard-plugins/pull/6160
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.7.0 (https://github.com/wazuh/wazuh-dashboard-plugins/releases).
- [x] Delete all stage tags for v4.7.0. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.7.0-rc1, 4.7.0-alpha1, etc.
- [x] Delete branch `4.7.0`.
- [x] Update [Compatibility Matrix](https://github.com/wazuh/wazuh-dashboard-plugins/wiki/Compatibility) in the repository wiki.

**Comment by Machi3mfl** [comment]
LGTM!
