### ISSUE TITLE
Support new stage RC 1 for 4.7.1 in wazuh-dashboard-plugins repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard-plugins#6153]
## Description

This issue attempts to support a new stage RC 1 for 4.7.1 in the wazuh-dashboard-plugins repository.

## Tasks

- [ ] Ensure changelog is updated for 4.7.1 (if applicable).
- [ ] Bump revision for branch 4.7.1 on wazuh-dashboard-plugins repository.
- [ ] Create tag v4.7.1-rc1 from branch 4.7.1 on wazuh-dashboard-plugins repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard-plugins/releases/tag/v4.7.1-rc1.
