### ISSUE TITLE
Refactor FIM dashboard

### ISSUE THREAD

**Issue by chantal-kelm** [wazuh/wazuh-dashboard-plugins#6178]
## Description

We want to refactor the FIM dashboard by removing all traces of angular, and implementing a new way of displaying dashboards using embeddable, which for the time being we only use in the new vulnerability dashboard.

## Tasks
The steps that have to be complete to close the issue.

- [x] Researching the FIM module
- [x] Analysing, learning about and becoming familiar with embeddables
- [x] Implement logic with embeddables for the FIM dashboard
- [ ] Apply logic to display the corresponding dashboard taking into account whether or not the user has a pinned agent
- [x] #6210 
- [x] Analysing components to be adapted to be reusable for use in FIM
- [x] #6325

## Additional information
Add here any additional information relevant to the issue or that will help to close it: chunks of code, logs, additional error messages, related issues and so on.

**Comment by chantal-kelm** [comment]
I am currently investigating the FIM module as agreed during the sync with @gdiazlo and @asteriscos in order to find out its use cases and improve its dashboards.

**Comment by chantal-kelm** [comment]
# **Use cases**

The Wazuh FIM module monitors directories to detect file changes, additions and deletions. This module is useful for monitoring important files on endpoints. You can use the FIM module for several purposes such as change management processes, regulatory compliance, and detecting cyberattacks. Below are examples of some use cases of the Wazuh FIM module.

[Detecting malware persistence technique](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/use-cases/detecting-malware-persistence-technique.html)
[Detecting account manipulation](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/use-cases/detecting-account-manipulation.html)
[Monitoring files at specific intervals](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/use-cases/monitoring-files-at-specific-intervals.html)
[Reporting file changes](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/use-cases/reporting-file-changes.html)
[Monitoring configuration changes](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/use-cases/monitoring-configuration-changes.html)


## How to best use existing use cases to create user-friendly dashboards?

- Based on what I read in the documentation [https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/index.html](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/index.htm) where it is mentioned that one of the capabilities of the FIM module is to be able to know which user modified a certain file, I think it would be useful to show this in a table in the Dashboard.

**Comment by asteriscos** [comment]
This change has been postponed.
