### ISSUE TITLE
[Remove embedded discover] Add all the necessary components to compose the new discover

### ISSUE THREAD

**Issue by Machi3mfl** [wazuh/wazuh-dashboard-plugins#6197]
## Description
Add all the necessary components to compose the new discover. 
Leave available all components in public/components/common

## Scope

Add all necessary components to create and compose a discover page using OSD native components like:
- Search Bar
- Data Grid
- Flyout with document details
- Events count histogram

Create a new discover component to reutilize it in all modules `events tab`(Threat hunting, Mitre, Malware detection, etc)

## Tasks

- [x] Add search_bar hook  
- [x] Add data_grid hook
- [x] Add doc_viewer component and hook
- [x] Add events count histogram
- [x] Create wazuh_discover components using above component

**Comment by Machi3mfl** [comment]
# New components available

## Search Bar

<img width="1381" alt="Screenshot 2023-12-12 at 10 30 59" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/a2374490-092c-4fd2-84d0-86135dfe97df">


## Data Grid

![Screenshot 2023-12-12 at 10 32 08](https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/89296e5a-4008-4307-864c-1a03e643551d)

## Doc Viewer 

![Screenshot 2023-12-12 at 10 32 29](https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/3be74f18-647b-4434-bb56-b11105289210)

## Wazuh discover

![Screenshot 2023-12-12 at 10 36 22](https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/8a746424-4d50-4fc3-a8a5-fd31bd02cf8d)
