### ISSUE TITLE
Support new stage RC 2 for 4.7.1 in wazuh-dashboard-plugins repository 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-dashboard-plugins#6199]
## Description

This issue attempts to support a new stage RC 2 for 4.7.1 in the wazuh-dashboard-plugins repository.

## Tasks

- [x] Ensure changelog is updated for 4.7.1 (if applicable).
- [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6200
- [x] Create tag v4.7.1-rc2 from branch 4.7.1 on wazuh-dashboard-plugins repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard-plugins/releases/tag/v4.7.1-2.8.0-rc2
