### ISSUE TITLE
[Remove embedded discover] Replace discover children components in vulnerabilities modules tab

### ISSUE THREAD

**Issue by Machi3mfl** [wazuh/wazuh-dashboard-plugins#6222]
## Description

Replace the `data_grid`, `search_bar`, and `doc_viewer` components for the same components placed globally in public/components/common added in https://github.com/wazuh/wazuh-dashboard-plugins/pull/6205 PR. And remove the duplicated components

<img width="152" alt="Screenshot 2023-12-14 at 15 37 30" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/b8cc048a-2e87-494f-a271-744f4a0fb46d">

## Tasks

- [x] Replace search_bar dependencies in Vulnerabilities Detector > Dashboard tab
- [x] Replace search_bar, data_grid, doc_viewer dependencies in Vulnerabilities Detector > Inventory tab
- [x] Remove data_grid, search_bar, doc_viewers folders from vulnerabilities folder
- [x] Check that all functionalities work as expected
