### ISSUE TITLE
Post release tasks for 4.7.1

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard-plugins#6233]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.7.1.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.7.1-into-4.7.2`.

## Tasks

- [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6240
- [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6241/
- [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6242
- [ ] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6243
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.7.1 (https://github.com/wazuh/wazuh-dashboard-plugins/releases).
- [x] Delete all stage tags for v4.7.1. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.7.1-rc1, 4.7.1-alpha1, etc.
- [x] Delete branch `4.7.1`.
- [x] Update [Compatibility Matrix](https://github.com/wazuh/wazuh-dashboard-plugins/wiki/Compatibility) in the repository wiki.
