### ISSUE TITLE
[Remove embedded discover] Replace discover on threat hunting module

### ISSUE THREAD

**Issue by Machi3mfl** [wazuh/wazuh-dashboard-plugins#6236]
## Description

Remove the embedded discover on Threat Hunting tabs and replace it with the new discover created with native OSD components (wazuh-discover component)

## Tasks

- [x] Use the new `wazuh-discover` component on the threat-hunting events tab
- [x] Optimize `wazuh-discover` component to make it more reusable
  - [x] Add histogram visualization
  - [x] Enhance column rendering to support custom call to actions
  - [x] Develop the _Save Query_ feature
- [x] Create necessary unit tests

**Comment by Machi3mfl** [comment]
## Replace `threat hunting` events tab

The `threat hunting` events tab content was replaced with the `new wz-discover` which is composed of native OSD components.

- SearchBar
- Histogram (Visualization)
- Data Grid
- Flyout (document details)

<img width="1440" alt="Screenshot 2023-12-29 at 01 42 22" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/57459199-9cc5-4a65-a729-cb0933de437d">

**Comment by Machi3mfl** [comment]
## New discover features detailed in https://github.com/wazuh/wazuh-dashboard-plugins/issues/6120#issuecomment-1841287226
