### ISSUE TITLE
Allow upgrade an agent from the actions table

### ISSUE THREAD

**Issue by lucianogorza** [wazuh/wazuh-dashboard-plugins#6253]
|Part of Epic|
|---|
|#6129|
## Description
We want to add new functionality to the agent table so the user can upgrade an agent from the actions column. Consider that the upgrade can be done using a WPK file from the online repository or a local WPK file.

## Tasks
- [x] Add upgrade action to actions column
- [x] Get outdated agents from displayed agents in list and if show outdates status in version column.
- [x] Only allow upgrade an agent if it is online and it is outdated.
- [x] Show summary upgrading agents status.

**Comment by lucianogorza** [comment]
## Update 27/02/2024

### Add upgrade action

![Image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/76307f94-52b4-4f89-b38a-afaad9f17180)

Disable upgrade action when agent is not active
![Image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/3b225118-1051-4d33-bbf3-e62fec146156)

**Comment by lucianogorza** [comment]
## Update 28/02/2024

### Disable upgrade action when agent is up to date
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/edfb4671-e952-4bbf-a25b-97edeac57504)

### Show outdated status in version column
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/a167aa6c-f083-4afb-85cf-d87fb030e7e5)

### Upgrade agent
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/f9cd42a4-688b-420e-b282-eb89fd93bfb4)
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/fca0334c-10d0-46ef-9cc2-1b21ec6ad9ac)
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/b3e8de03-3926-4dcf-9208-6a035f1cbc7c)

**Comment by lucianogorza** [comment]
## Update 01/03/2024
### Upgrade 1 agent and update progress
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/808a2fa4-d3ca-479a-aa6b-8b5dc4b4cfc1)
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/01dd8472-f378-437b-af73-cccda0e95cc4)

**Comment by lucianogorza** [comment]
## Update 04/03/2024

### Upgrade progress and show total errors last 60 minutes
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/b64bc217-1d06-4485-9320-ea43ea1e0337)

**Comment by lucianogorza** [comment]
## Update 06/03/2024
### Improve user feedback
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/688ab2cc-63c0-4cb3-9351-d83ece134b6c)
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/a83b070e-4fa1-4e50-862e-d65194d26240)
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/4f2c4cdc-0f03-467f-8609-70384e2a2d91)
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/be6210be-b55a-4b5b-8003-7376aca58c12)
