### ISSUE TITLE
Allow select agents to add or remove groups

### ISSUE THREAD

**Issue by lucianogorza** [wazuh/wazuh-dashboard-plugins#6257]
|Part of Epic|
|---|
|#6129|
## Description
We want to add new functionality to the agent table so the user can select agents and assign them to groups, or create a new group for those agents.
Also, we want to allow the user to remove groups from agents.

## Tasks
- [x] Add a selector to the agent table rows
- [x] Add toast when editing groups from a table row
- [x] Add global action `Add groups to agents`
- [x] Add global action `Remove groups from agents`
- [x] Result modal must show results and errors.
- [x] Fix filters when user type
- [x] After refreshing the table or changing the page the selection must reset.
- [x] Paginate API requests
  - [x] Get agents
  - [x] Get groups
  - [x] Add agents to group
  - [x] Remove agents from group
- [x] Unit tests

### Without row check

- Advantage
  - Actions can be applied to all agents matching the applied filter, which may be more than those shown on the current page, providing the user with agility to operate with a considerable number of agents.

- Disadvantage
  - It may happen that when applying the global action, the total number of agents obtained according to the filter differs from the total shown in the previously retrieved list. For this reason, the help tooltip is added to the "Total agents" label.
  
![Global actions - without select - 01](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/81248730-9467-4b65-91d8-7f2fa3e8e60c)
![Global actions - without select - 02](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/1ca8ae6f-8d1b-4ed8-9fe8-45c4410927ea)
![Global actions - without select - 03](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/d3664b4f-be0e-4bea-bf11-771bf7ae9a31)

### With row check
- Advantages
  - The selection of agents on which global actions are applied is more transparent to the user.
  - There will never be inconsistencies between what is seen in the table and the agents on which actions will be applied.
  
- Disadvantage
  - Global actions are limited to the agents shown on the page. Even if all agents are selected with the upper checkbox, only those displayed are selected.
  
![Gloabal actions - with select - 01](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/cab8f150-4492-42d4-bd50-258b8dc39e9b)

### With row check and select all rows
- Advantages
  - The selection of agents on which global actions are applied is more transparent to the user.
  - Actions can be applied to all agents matching the applied filter, which may be more than those shown on the current page, providing the user with agility to operate with a considerable number of agents.
   
- Disadvantage
  - It may happen that when applying the global action, the total number of agents obtained according to the filter differs from the total shown in the previously retrieved list.
 
![Remove groups grom agents](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/c4430d51-47a1-4f08-81ab-1c632d4515d5)

**Comment by lucianogorza** [comment]
## Update 02/02/2024

### Callout to warning user about agent selection

When select all filtered agents the modal shows a callout

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/897a46d6-48c7-4972-9feb-c5066f2d61ac)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/3705ede3-75e0-4c0f-85cd-5bce51615acd)

**Comment by lucianogorza** [comment]
## Update 05/02/2024
Callout when selecting all agents and get error on retrive
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/976d9f6e-cd40-4c7d-841c-798096f59dc5)

**Comment by lucianogorza** [comment]
## Update 19/02/2024

### Fix filters  and clear selection on sort and pagination
[agent-filters.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/4dfa4e39-096a-4ac5-99ae-73353b866045)

**Comment by lucianogorza** [comment]
## Update 21/02/2024 (Paginate API requests)

> Only for test purpose, I used a page size = 2.

### 1. Select all filtered agents

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/67e1d22e-46dd-4ee5-a0cf-caadb4117bce)

### 2. Open add agents to group modal

#### Get all groups paginated.
Total groups = 3
Page size = 2
Total requests = 2

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/303e4425-90c8-47c6-9d30-a2b1928e8c79)
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/08271225-485a-4d4a-b3a6-53060e94b107)


### Paginate get agents request
