### ISSUE TITLE
Refactoring and redesign Endpoints Summary charts

### ISSUE THREAD

**Issue by jbiset** [wazuh/wazuh-dashboard-plugins#6258]
|Part of Epic|
|---|
|#6129|

## Description
The Endpoints Summary charts need to be refactored and redesigned. 

> [!NOTE]  
> Due to possible API changes, the performance of the endpoints used in the visualizations of this task must be taken into account.

## Tasks
For this, the following is proposed:
- [x] Refactor the Agents by Status graph, so that it is a decoupled and reusable component for other similar Endpoints Summary graphs.
- [x] Develop the Agents by OS graph, reusing the refactored Agents by Status component.
- [x] Develop the Agents by Group graph, reusing the refactored Agents by Status component.
- [x] Develop a card that shows the number of outdated agents.
- [x] The previous points must provide functionality, so that when interacting with them it can be filtered in the table below in Endpoints Summary.
- [x] Analyze and implement a mechanism for generating chart colors based on the OpenSearch Dashboard UI library.
- [x] Check responsive layout.
- [x] Refactor `/agents/stats/distinct` endpoint if necessary in the imposter.
- [x] Add tests

**Comment by jbiset** [comment]
## Initial proposal for the redesign of Endpoints summary charts

### Endpoints summary screen
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/453bfe72-ab41-43f4-ba7c-235e27bee796)


### Endpoints summary screen with outdated agents popover opened
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/966af159-a5cf-4f41-8d69-942e97d29f5b)
