### ISSUE TITLE
Support new stage Alpha 2 for 4.8.0 in wazuh-dashboard-plugins repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard-plugins#6283]
## Description

This issue attempts to support a new stage Alpha 2 for 4.8.0 in the wazuh-dashboard-plugins repository.

## Tasks

- [x] Ensure changelog is updated for 4.8.0 (if applicable).
- [x] Bump revision for branch 4.8.0 on wazuh-dashboard-plugins repository. 
  - https://github.com/wazuh/wazuh-dashboard-plugins/pull/6284
- [x] Create tag v4.8.0-alpha2 from branch 4.8.0 on wazuh-dashboard-plugins repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard-plugins/releases/tag/v4.8.0-2.10.0-alpha2

**Comment by jbiset** [comment]
LGTM!
