### ISSUE TITLE
Remove IT hygiene section

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-dashboard-plugins#6360]
## Description

We want to remove the IT Hygiene from the menu until the data is uploaded to the indexer in future releases. We want to bring back the old behaviour of the agents page, including the top menu.

We expect that by removing the IT Hygiene menu entry, the breadcrumb will be usable in the endpoint summary section, which will allow us to re-enable the bar menu we had in the section.

## Tasks
The steps that have to be completed in order to close the issue.

- [x] Remove It Hygiene menu entry
- [x] Add the navigation bar to the endpoint summary section again
- [x] Check the breadcrumb works
