### ISSUE TITLE
Refactor the home section top kpi

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-dashboard-plugins#6367]
## Description

We want to refactor the top section of the home section, removing unwanted data and adding new one.
- Remove the `Total agents `indicator
- Remove the` Pending agents `indicator
- Remove the `Never connected agents` indicator
- Add `Last 24 hours alerts` count, clicking in the count will go to the platform discover with the last 24 hours event filtered.

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/2181918/574b7f2a-e250-42e6-9aca-136b579294f7)

## Tasks
The steps that have to be completed in order to close the issue.

- [ ] Remove the `Total agents `indicator
- [ ] Remove the` Pending agents `indicator
- [ ] Remove the `Never connected agents` indicator
- [ ] Add `Last 24 hours alerts` count

## Additional information

We must pay attention the performance of the query used to calculate the last 24 hours alerts count
