### ISSUE TITLE
Remove duplicated links from help menu

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-dashboard-plugins#6368]
## Description

We want to simplify the help menu, because over the years, we've ended duplicating some of the links:

HELP
v4.8.0
[Documentation](https://documentation.wazuh.com/4.8)
[Community](https://wazuh.com/community/join-us-on-slack)
[Give feedback](https://wazuh.com/community/join-us-on-slack)
[Open an issue in GitHub](https://github.com/wazuh/wazuh/issues/new/choose)
Wazuh support
[ Documentation](https://documentation.wazuh.com/4.8/)
[ Slack channel](https://wazuh.com/community/join-us-on-slack)
[ Projects on Github](https://github.com/wazuh)
[ Google Group](https://groups.google.com/forum/#!forum/wazuh)

We want to simplify it to:

HELP
v4.8.0
[Documentation](https://documentation.wazuh.com/4.8)
[ Slack channel](https://wazuh.com/community/join-us-on-slack)
[ Projects on Github](https://github.com/wazuh)
[ Google Group](https://groups.google.com/forum/#!forum/wazuh)

The motivation for this changes are:
- Documentation will remain as it is, pointing users to our extensive documentation library
- Community is too broad to cover with a single link, so we want to provide links to our most used channels (slack and google groups), there are other channels like reddit and discord which are also popular.
- We want to link to the GitHub org so interested users can reach the all our open source projects

## Tasks

- [x] https://github.com/wazuh/wazuh-packages/pull/2796
- [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6374
- [x] https://github.com/wazuh/wazuh-dashboard/pull/139

**Comment by Tostti** [comment]
# Research 
The current menu is this 
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/bb56ba80-e949-4f81-a869-f453d504d75e)

The duplication happens because the upper section is from Wazuh Dashboard itself, while the other section is added on the plugin
https://github.com/wazuh/wazuh-dashboard-plugins/blob/20b4770defda9050af0f13d663d614b52396be30/plugins/main/public/app.js#L106

Moreover, this causes an inconsistency in the menu, because if the user is outside the main Wazuh plugin, the menu will only be the upper section of the previously shown: 
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/7cd21e4a-f164-4cfa-929b-025e96166d5f)

# Proposed solution
The solution should fix the menu and also make it consistent through all the application. To do that, the proposed steps are:

1. Change the menu in the package building on the `wazuh-packages` repo.
2. Remove the added menu in the Wazuh app. 

Additionally, considering that in the future the package will be built in the `wazuh-dashboard` repo, it will be a nice to also apply the changes there.
