### ISSUE TITLE
Move the plugin registry to stateless

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-dashboard-plugins#6387]
# Description

As part of the issue that pretends to remove the stateful of the Wazuh dashboard plugins, we need to replace the way the data of the plugin's registry is stored so this doesn't use a file in the filesystem of the application.

Currently, this data is stored in the `wazuh-registry.json` file located at `<Wazuh Dashboard>/data/wazuh/config/wazuh-registry.json.

The data related to the API hosts will be stored in an in-memory cache managed instead. Any action about the API host configuration should update the registry data of the host.

# Tasks

- [x] Analyze the stored data in the registry file https://github.com/wazuh/wazuh-dashboard-plugins/issues/6387#issuecomment-1966213961
- [x] Propose the new store system https://github.com/wazuh/wazuh-dashboard-plugins/issues/6387#issuecomment-1980866235
- [x] Implement the new store system based on in-memory-cache
  - [x] Implement the cache on the `ManageHosts` service that will store information about the registry
  - [x] Remove the `UpdateRegistry` file
  - [x] Initializes the cache with the API hosts at start
  - [x] Move and remove the logic to update the registry from the frontend side to the backend side

**Comment by Desvelao** [comment]
# Analisys

## Description

The usage of the file is referenced here: https://github.com/wazuh/wazuh-dashboard-plugins/issues/1465#issuecomment-516350091

The current look of this file:
```json
{"name":"Wazuh dashboard","app-version":"4.9.0","revision":"00","installationDate":"2024-02-26T16:28:27.840Z","lastRestart":"2024-02-26T16:28:27.840Z","hosts":{"imposter":{"cluster_info":{"manager":"wazuh-manager-master-0","node":"master-node","cluster":"wazuh","status":"enabled","allow_run_as":2}}}}
```

## Stored data
- App metadata:
  - Name
  - Version
  - Revision
  - Installation date
  - last restart
- Cluster information of the API hosts:
  - Manager
  - Node name
  - Cluster name
  - Status
  - Allow run as

## Usage

The data related to the hosts is updated through the frontend or backend side (based on the current status of `4.9.0` development branch):

- Frontend:
  - Server APIs when checking the connection to an API
  - Server APIs table when using the refresh button
  - API host selector when changing the API host
  - API is down view when checking the connection

I am not sure because the cluster info is set through the frontend side instead of done by the backend side. All the actions use the `GET /hosts/update-hostname/{id}` API endpoint.

For this case, the data is comming from the `GET /apis/checkapi` API endpoint

- Backend:
  - When checking the stored API of a client
  - API endpoints:
    - `GET /api/setup`: unused by frontend side
    - `GET /api/timestamp`: unused by frontend side
  
## Service

The management of registry file `wazuh-registry.json` is managed through the `UpdateRegistry` service. This has methods to:
- Read content
- Get data related to hosts (all or by ID)
- Write content
- Check if the host with ID exist
- Migrate to registry
- Update cluster info
- Update API extensions
- Remove host entries
- Remove orphan entries
- Get token by ID
- Update token by ID

Unused methods that could be removed:
- Get data related to hosts only for ID
- Check if the host with ID exist
- Migrate to registry
- Update API extensions
- Get token by ID
- Update token by ID

**Comment by Desvelao** [comment]
# Changes

- Remove unused API endpoint GET /api/timestamp
- Remove unused fields and unwanted from registry file
- Remove unused methods of UpdateRegistry service
- Adapted GET /api/setup to use version and revision information of plugin definition instead of stored in the registry file

**Comment by Desvelao** [comment]
# Design

We will apply the following actions to the registry data:
- Remove the plugins metadata:
  - Name
  - Version
  - Revision
  - Installation date
  - last restart
- Move the cluster info to another store system based on in-memory cache
  
> Note: Version and revision will be used from the package manifest instead.

The cluster info about the API hosts will be managed by the `ManageHost` service using an in-memory cache.

The cache stores information about the API host data:

```ts
interface IAPIHostRegistry {
  manager: string | null;
  node: string | null;
  status: string;
  cluster: string;
  allow_run_as: API_USER_STATUS_RUN_AS;
}
```

When the plugin starts, the `ManageHosts` service initiates the cache getting the data from the API hosts.

We will move the cache related to the `allow_run_as` for each API from the `cacheAPIUserAllowRunAs` to the cache of the registry.

This approach causes the `UpdateRegistry` service that managed the update of the registry file to be not needed anymore, so this will be removed.

The logic related to updating the cluster info in the registry and removing orphan entries in the registry is done by the frontend side, it is moved to the backend side.

**Comment by Desvelao** [comment]
# Changes

- Update changelog of pull request https://github.com/wazuh/wazuh-dashboard-plugins/pull/6481
