### ISSUE TITLE
Wazuh packages redesign tier 1 - Stage 2 - Migrate and adapt the Wazuhapp

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh-dashboard-plugins#6411]
## Description
We are on an effort to modernize the packages' generation and lifecycle. This issue aims to track the effort to migrate the packages' generation process from the wazuh-packages repository and automate its generation, testing and delivery steps of their lifecycle.

The tasks listed below are extracted from https://github.com/wazuh/internal-devel-requests/issues/712. Use that issue for additional information and requirements.

## Tasks

- [x] Migrate code into target repository for manual package generation
    - https://github.com/wazuh/wazuh-dashboard-plugins/pull/5305 
- [x] Automate packages generation through CI
    - https://github.com/wazuh/wazuh-dashboard-plugins/pull/4680
    - https://github.com/wazuh/wazuh-dashboard-plugins/issues/6108
    - https://github.com/wazuh/wazuh-dashboard-plugins/issues/6194
- [x] Automate packages testing through CI
    - https://github.com/wazuh/wazuh-dashboard-plugins/pull/6508
- [x] ~Add secrets to GH (to upload packages to S3)~
- [x] ~Upload packages to S3 through CI~

**Comment by rauldpm** [comment]
First estimated ETA provided by @Tostti : `2024/03/22`

**Comment by rauldpm** [comment]
@Tostti after a meeting with @davidjiglesias it has been decided that the plugin files will not be uploaded nor released, you can skip the CI upload task

Secrets removed from the repository

**Comment by Tostti** [comment]
All steps successfully completed
