### ISSUE TITLE
Wazuh packages redesign tier 1 - Stage 2 - Migrate and adapt the ELK templates

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh-dashboard-plugins#6412]
## Description
We are on an effort to modernize the packages' generation and lifecycle. This issue aims to track the effort to migrate the packages' generation process from the wazuh-packages repository and automate its generation, testing and delivery steps of their lifecycle.

The tasks listed below are extracted from https://github.com/wazuh/internal-devel-requests/issues/712. Use that issue for additional information and requirements.

## Tasks

- [ ] Migrate code into target repository for manual package generation
- [ ] Automate packages generation through CI
- [ ] Automate packages testing through CI
- [ ] Add secrets to GH (to upload packages to S3)
- [ ] Upload packages to S3 through CI

**Comment by rauldpm** [comment]
After a meeting with the teams involved, it has been decided to close this issue as not planned because no references to those files were found in the actual version, this will be revisited in the future with the wazuh-packages repository review
