### ISSUE TITLE
Support new stage RC 2 for 4.7.3 in wazuh-dashboard-plugins repository 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-dashboard-plugins#6449]
## Description

This issue attempts to support a new stage RC 2 for 4.7.3 in the wazuh-dashboard-plugins repository.

## Tasks

- [x] Ensure changelog is updated for 4.7.3 (if applicable).
  - https://github.com/wazuh/wazuh-dashboard-plugins/pull/6456
- [x] Create tag v4.7.3-rc2 from branch 4.7.3 on wazuh-dashboard-plugins repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard-plugins/releases/tag/v4.7.3-2.8.0-rc2.

We need to retag to include this fix:
- https://github.com/wazuh/wazuh-dashboard-plugins/pull/6458

**Comment by Tostti** [comment]
LGTM
