### ISSUE TITLE
Add via SYSLOG reporting Devices and SYSLOG Config to GUI

### ISSUE THREAD

**Issue by No1234DDgg** [wazuh/wazuh-dashboard-plugins#6461]
## Description
GUI additions for syslog usage and configuration

## Tasks

- [ ] Add SYSLOG reporting devices to GUI
- [ ] Add SYSLOG Config to GUI
- [ ] simple way to assign a parser/decoder for SYSLOG reporting devices

thx Guys :)
