### ISSUE TITLE
ADD IOT Scanner for the Agents

### ISSUE THREAD

**Issue by No1234DDgg** [wazuh/wazuh-dashboard-plugins#6463]
## Description
add an IOT/ Network Scanner that scans scheduled or on command the agents network for other devices.   

## Tasks
The steps that have to be completed in order to close the issue.

- [ ] add networkscanner via Agent
- [ ] implement a usable GUI interface for the Scans
- [ ] predefined report generator for "non managed Devices"
- [ ] implement Device recognition based on Vendor spezific macadresses
