### ISSUE TITLE
Add support for Email parsers/decoder

### ISSUE THREAD

**Issue by No1234DDgg** [wazuh/wazuh-dashboard-plugins#6464]
## Description
Some devices and applications are not be able to export their Data via syslog or throu the windows Events. For that reason would a Email parser/decoder very usefull. 

## Tasks
The steps that have to be completed in order to close the issue.

- [ ] implement a Email parser
- [ ] implement a usable WEB-GUI tab for this feature
- [ ] parser/decoder configurable via web gui

## Additional information
for example
Quest Active Administrator can't send via syslog. Only via email are reports and alerts exportable.
