### ISSUE TITLE
[Remove discover] Refactor modules dashboards with new embeddable component

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6477]
## Description
We need to refactor all the module's dashboards that use the legacy discover methods to render visualization. To refactor these dashboards we have to implement the new dashboard embeddable component in each of the modules. This will allow us to progressively deprecate the legacy discover dependencies and give one step forward to standardize the filtering mechanisms and also deprecate AngularJS in the plugins.

## Tasks

- [x] #6478
- [x] #6479
- [x] #6500
- [x] #6493
- [x] #6503
- [x] #6522
- [x] #6524
- [x] #6502
- [x] #6505
- [x] #6507
- [x] #6514
- [x] #6516
- [x] #6480
- [x] #6511
- [x] #6520
- [x] #6530
- [x] #6532
- [x] #6600 
- [x] #6608 
- [x] #6647

**Comment by jbiset** [comment]
## Research

Office and Github use `plugins/main/public/components/common/modules/panel/main-panel.tsx`, these modules should be analyzed particularly.

Depending on whether it is overview or pinned agents, main-panel uses the static methods of `plugins/main/public/react-services/vis-factory-handler.js` to create the visualizations.

The component attribute that is defined in modules-default for each module specifies the dashboard to render, based on whether it is overview or agent, it is rendered in `plugins/main/public/components/common/modules/main-overview.tsx` or `plugins /main/public/components/common/modules/main-agent.tsx` accordingly. It is `plugins/main/public/components/common/modules/main.tsx` that is responsible for finally calling main-overview or main-agent depending on whether an agent is pinned or not.


Several dashboards in modules-default are rendered through a Dashboard component (`plugins/main/public/components/common/modules/dashboard.tsx`) that, despite returning null in the rendering, sends the corresponding visualizations to be rendered (It is being analyzed ). Surely ModulesHelper is the one who is called to finally render according to the section to be rendered that the Dashboard receives as a prop

The KivanaVis acts as the panel for the new DashboardByRenderer rendering method.

Based on the above, so far the best strategy is to work creating dashboard components according to each module and use it in modules-defaults.js (`plugins/main/public/components/common/modules/modules-defaults.js`) in a way similar to what was proposed with Vulnerabilities and FIM.

**Comment by JuanGarriuz** [comment]
## Research

To consider for dashboards:
- [ ] Each visualization, if applicable, must have interaction in such a way that it adds the corresponding filter(s) when clicked.
- [ ] Visualizations must update according to the filters applied in the searchbar.
- [ ] Visualizations must update when a search is performed in the searchbar.
- [ ] If there are no results, the corresponding message that there are no results should appear, and the visualizations should not be rendered.
- [ ] If there is SampleData, the corresponding SampleData message should appear.
- [ ] If an agent is pinned, the visualizations must update and change to the agent one, if applicable.

**Comment by jbiset** [comment]
## Updated considerations for dashboards

- Each visualization, if applicable, must have interaction so that it adds the corresponding filter(s) upon clicking.
- The visualizations have to be updated according to the filters applied in the searchbar.
- The visualizations have to be updated when a search is performed in the searchbar.
- If there are no results, the corresponding message must appear that there are no results and the visualizations should not be rendered.
- If there is SampleData, the corresponding SampleData message must appear.
- If an agent is pinned, the views must be updated and changed to the agent view, if applicable.  
- Check filter behavior with respect to `hide alerts`, `allow agents` and filter order.
