### ISSUE TITLE
[Remove discover] Refactor dashboard, intelligence, framework and events tabs on MITRE ATT&CK module

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6480]
## Description

We have to implement the embeddable dashboard on MITRE ATT&CK -> dashboard tab and deprecate any use of _kibana-integrations_ components.

## Plan

- Detailed in comment:  https://github.com/wazuh/wazuh-dashboard-plugins/issues/6480#issuecomment-2044704232

**Comment by JuanGarriuz** [comment]
## Update 07/03


![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/7fadcb9c-b717-4ade-81c9-cac90bfa5a00)


- The dashboard has been completely replaced.
- The use of samplealert is being investigated.
- The development of switching the dashboard when pinging an agent is being investigated for future releases.

**Comment by Machi3mfl** [comment]
## Tasks

- [ ] Apply the new data source solution to the Dashboard Tab
- [ ] Apply the new data source solution to the Events Tab
- [ ] Apply the new data source solution to the Intelligence Tab
- [ ] Apply the new data source solution to the Framework Tab

**Comment by Desvelao** [comment]
# Research

I was researching a problem with the search context of detail flyouts of techniques on `Framework` tab. I shared a patch to fix this problem @Machi3mfl.

I found more problems we should solve:
- The `useSearchBar` hook is using the global instance of query (conditionally, but it could apply to the most of the use cases we have implemented) and timefilter. This does not allow to separate the context of the search.
