### ISSUE TITLE
Minor style improvements

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6483]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 05 | - |

## Description

There are a few minor aesthetic improvements to be made for 4.8.0. 

## Tasks

- [ ] Change the grey background to #fafbfd00 in 
  - Overview
  - SCA
  - App settings
  - Server APIs
- [ ] VirusTotal must have a capital T in the global menu
- [ ] Dashboard management must be the last item of the global meno and Indexer management should be before it.
