### ISSUE TITLE
Allow select agents and trigger a bulk upgrade

### ISSUE THREAD

**Issue by lucianogorza** [wazuh/wazuh-dashboard-plugins#6496]
|Part of Epic|
|---|
|#6129|
## Description
We want to add new functionality to the agent table so the user can select agents and trigger a bulk upgrade.
The user must have the ability to access the list of upgrade tasks at all times to check their status.

## Tasks
- [x] Restructure global actions in a new menú.
- [x] Move `Upgrade task details` modal to global actions.
- [x] Allow close upgrade panel
- [x] Add global action `Upgrade agents`
- [x] Result modal must show results and errors.
- [x] Paginate API requests for upgrade
- [x] Unit tests

**Comment by lucianogorza** [comment]
## Update 11/03/2024

### Restructure global actions in a new menú.

**Comment by lucianogorza** [comment]
## Update 12/03/2024

### Result modal must show results and errors

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/ce9632ee-e7cc-4cb8-bf2c-9d1effd3da1c)

### Select all filtered agents

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/446d065e-d102-43f5-b7de-057769275b63)
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/7fd2b7f2-d404-4685-84a7-37f05ab9a0cd)
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/4872acaa-b772-4794-9560-f18d83d33d4d)

**Comment by lucianogorza** [comment]
## Update 15/03/2024

### Add tooltip for Timeout task status

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/94adf6a6-1f81-440f-a50d-12b1e1c7d88e)
