### ISSUE TITLE
[Remove discover] Implement embeddable dashboard on Docker module

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6500]
## Description

We have to implement the embeddable dashboard on Docker -> dashboard tab and deprecate any use of _kibana-integrations_ components.

> [!WARNING]  
> The embeddable panel id must be unique including general and agents visualizations. Otherwise, the visualizations will not refresh when we pin an agent, because they are cached by id

## Tasks
- [x] Implement the embeddable dashboard on Docker -> dashboard tab
  - [x] Migrate visualizations to embeddable panels
  - [x] Add new searchbar
  - [x] Migrate bottom table to new discover
  - [x] Add SampleDataMessage
  - [x] Add conditionality to show the dashboard if there are results.
  - [x] Add loadings
  - [x] Add message that there are no results
- [x] Check the following:
  - [x] Each visualization, if applicable, must have interaction so that it adds the corresponding filter(s) upon clicking.
  - [x] The visualizations have to be updated according to the filters applied in the searchbar.
  - [x] The visualizations have to be updated when a search is performed in the searchbar.
  - [x] If there are no results, the corresponding message must appear that there are no results and the visualizations should not be rendered.
  - [x] If there is SampleData, the corresponding SampleData message must appear.
  - [x] If an agent is pinned, the views must be updated and changed to the agent view, if applicable.  

## Source task
- #6477
