### ISSUE TITLE
[Remove discover] Implement embeddable dashboard on PCI DSS module

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-dashboard-plugins#6502]
## Description

We have to implement the embeddable dashboard on PCI DSS -> dashboard tab and deprecate any use of _kibana-integrations_ components.

## Tasks

- [x] Implement the embeddable dashboard on PCI DSS -> dashboard tab
  - [x] Implement the usage of DataSoruce
- [x] Refactor the `Controls` tab to use Data Source
  - [x] Main view
  - [x] Flyout
    - [x] Replace table by WzDiscover and DataSource

**Comment by Desvelao** [comment]
# Update

From 2024-04-09, I am working into refactoring the `Controls` tab to use the DataSource interface and replace the search bar for using `useSearchBar` and the native search bar.

I found some unsupported use cases for the data source that should be resolved to continue. These are affecting to the regulatory compliance and MITRE ATT&CK apps.

Today, I am researching on the common issues that should be solved that allow us to replace the previous components with new ones.

**Comment by Desvelao** [comment]
# Changes

- Minor comment enhancements
- Add date range to the Dashbooard query
- Remove visualizations on server side

**Comment by Desvelao** [comment]
# Changes
- Update the development branch.
- Fix hide filter control on the Dashboard tab.

**Comment by Desvelao** [comment]
# Changes
- Fix missing filter related to the selected requirement on the flyout of the `Controls` tab
