### ISSUE TITLE
[Remove discover] Implement embeddable dashboard on GDPR module

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-dashboard-plugins#6505]
## Description

We have to implement the embeddable dashboard on GDPR -> dashboard tab and deprecate any use of _kibana-integrations_ components.

## Tasks

- [x] Implement the embeddable dashboard on GDPR -> `Dashboard` tab
- [x] Implement the embeddable dashboard on GDPR -> `Controls` tab
- [x] Implement the embeddable dashboard on GDPR -> `Events` tab

**Comment by Desvelao** [comment]
# Changes

- Implement DataSource on Dashboard and Events tabs
- Prepare to use DataSource on Controls tab. It depends on the changes on https://github.com/wazuh/wazuh-dashboard-plugins/pull/6504
- Replace the usage of NoResults and LoadingSpinner components by the common instead of the local ones

**Comment by Desvelao** [comment]
# Changes

- Minor comment enhancements
- Add date range to the Dashbooard query
- Remove visualizations on server side

**Comment by Desvelao** [comment]
# Changes
- Update the development branch.
- Fix hide filter control on the Dashboard tab.

**Comment by Desvelao** [comment]
# Changes
- Update the development branch with the latest changes of `4.9.0`

**Comment by Desvelao** [comment]
# Changes
- Update the development branch with the latest changes of `4.9.0`
- Research a problem with repeated filters in the queries of Regulatory compliance > Controls > flyout and MITRE ATT&CK > Framework > flyout
- Fix repeated request on Regulatory complicance > Controls > flyout and MITRE ATT&CK > Framework > flyout
