### ISSUE TITLE
[Remove discover] Implement embeddable dashboard on HIPAA module

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-dashboard-plugins#6507]
## Description

We have to implement the embeddable dashboard on HIPAA -> dashboard tab and deprecate any use of _kibana-integrations_ components.

## Tasks

- [x] Implement the embeddable dashboard on HIPAA -> `Dashboard` tab
- [x] Implement the embeddable dashboard on HIPAA -> `Controls` tab
- [x] Implement the embeddable dashboard on HIPAA -> `Events` tab

**Comment by Desvelao** [comment]
# Changes

- Implement DataSource on Dashboard and Events tabs
- Prepare to use DataSource on Controls tab. It depends on the changes on https://github.com/wazuh/wazuh-dashboard-plugins/pull/6504
- Replace the usage of NoResults and LoadingSpinner components by the common instead of the local ones

**Comment by Desvelao** [comment]
# Changes

- Minor comment enhancements
- Add date range to the Dashbooard query
- Remove visualizations on server side

**Comment by Desvelao** [comment]
# Changes

- Minor comment enhancements
- Add date range to the Dashbooard query
- Remove visualizations on server side

**Comment by Desvelao** [comment]
# Changes
- Update the development branch.
- Fix hide filter control on the Dashboard tab.
