### ISSUE TITLE
[Remove discover] Implement embeddable dashboard on Virustotal module

### ISSUE THREAD

**Issue by jbiset** [wazuh/wazuh-dashboard-plugins#6511]
## Description

We have to implement the embeddable dashboard on Virustotal -> dashboard tab and deprecate any use of _kibana-integrations_ components.

> [!WARNING]  
> The embeddable panel id must be unique including general and agents visualizations. Otherwise, the visualizations will not refresh when we pin an agent, because they are cached by id

<details>
<summary>
Current VirusTotal screens
</summary>

![Virustotal-A](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/2514a03e-992a-4746-b02a-61dcaf7c399d)

![Virustotal-B](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/0070a4c6-5868-4099-8daa-e0a1bfa9eb75)

![Virustotal-C](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/fb7f01ef-eb58-4a00-b5d3-b61576dcebc4)

![Virustotal-A_pinnedAgent](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/8c6d9a3e-c016-40be-be27-02771c3dee19)

</details>

## Tasks
- [x] Implement the embeddable dashboard on Virustotal -> dashboard tab
  - [x] Migrate visualizations to embeddable panels
  - [x] Add new searchbar
  - [x] Add SampleDataMessage
  - [x] Add conditionality to show the dashboard if there are results.
  - [x] Add loadings
  - [x] Add message that there are no results
  - [x] Change index pattern selection mechanism (Dependence: https://github.com/wazuh/wazuh-dashboard-plugins/issues/6434)
  - [x] Change pinned agent recognition mechanism (Dependence: https://github.com/wazuh/wazuh-dashboard-plugins/issues/6499)
  - [x] Once the two previous points have been applied, corroborate filter behavior with respect to `hide alerts`, `allow agents` and filter order.
- [x] Check the following:
  - [x] Each visualization, if applicable, must have interaction so that it adds the corresponding filter(s) upon clicking.
  - [x] The visualizations have to be updated according to the filters applied in the searchbar.
  - [x] The visualizations have to be updated when a search is performed in the searchbar.
  - [x] If there are no results, the corresponding message must appear that there are no results and the visualizations should not be rendered.
  - [x] If there is SampleData, the corresponding SampleData message must appear.
  - [x] If an agent is pinned, the views must be updated and changed to the agent view, if applicable.  
  - [x] Check filter behavior with respect to `hide alerts`, `allow agents` and filter order.

## Source task
- #6477

**Comment by jbiset** [comment]
## Update 15/03/2024

The following is resolved:

- Migrated visualizations to embeddable panels
- Added new searchbar
- Added SampleDataMessage
- Added conditionality to show the dashboard if there are results.
- Added loadings
- Added message that there are no results

### Evidence

[Evidence_updates.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/f90bb75a-3d1a-4d4d-93f0-ff5993667a82)


**NOTE:** In the Virustotal dashboard without having the agent pinned, it is proposed to change "Unique malicious files per agent" to "Top 5 agents with unique malicious files" since it better reflects what is being shown.

_The task is blocked until the dependencies are resolved_

**Comment by jbiset** [comment]
## Update 15/04/2024

- Functionality of the new data source is integrated by creating an alerts-virustotal-data-source
- Common NoResults component is incorporated
- Common LoadingSpinner component is incorporated
- Conditionals are adjusted in the dashboard according to the data source

### TO DO:

- Fix implicit/fixed virustotal filters
- Fix Events tab with new data source

### Current screen
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/e6df4c4f-ecc0-4425-b75a-2796bc8ebb23)

**Comment by jbiset** [comment]
## Update 17/04/2024

### Changed pinned agent recognition mechanism according to the new data source

[Evidence_pinnedAgent.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/543dc376-d020-45c7-8446-4497163b7275)

**Comment by jbiset** [comment]
## Update 18/04/2024

- Added timeRange to dashboard useEffect dependencies
- Changed the way to get pinned agent
- The problem of why the `AppState.clusterInfo` is not updated correctly is analyzed. Since when exchanging between `manager` and `cluster` mode it usually happens that the value does not change and the enabled cluster remains in manager mode. However, the problem is not particular to this Issue, as well as the problem of implicit/fixed filters that do not eliminate the "x"
- The evidence of the PR is completed and it is placed in Pending review

**Comment by jbiset** [comment]
## Update 24/04/2024

- Changed AlertsVirustotalDataSource import in modules-defaults
- Fixed error message
- DashboardByRenderer timeRange params replaced by searchBarProps deconstruction
- Added hide-filter-control classes to hide the button thatallows you to affect all the filters in the search bar
- Removed unnecessary virustotal in tabFilters in common data to remove duplicate filters
- Removed unused files
- Added dateRange param to fetchData in dashboard useEffect
