### ISSUE TITLE
[Remove discover] Implement embeddable dashboard on TSC module

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-dashboard-plugins#6516]
## Description

We have to implement the embeddable dashboard on TSC -> dashboard tab and deprecate any use of _kibana-integrations_ components.

## Tasks

- [x] Implement the embeddable dashboard on TSC -> `Dashboard` tab
- [x] Implement the embeddable dashboard on TSC -> `Controls` tab
- [x] Implement the embeddable dashboard on TSC -> `Events` tab

**Comment by Desvelao** [comment]
# Changes

- Minor comment enhancements
- Add date range to the Dashbooard query
- Remove visualizations on server side

**Comment by Desvelao** [comment]
# Changes
- Update the development branch.
- Fix hide filter control on the Dashboard tab.
