### ISSUE TITLE
[Remove discover] Implement embeddable dashboard on Github module

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-dashboard-plugins#6522]
## Description

We have to implement the embeddable dashboard on GitHub -> dashboard tab and deprecate any use of _kibana-integrations_ components.

## Tasks

- [x] Move panel definition to the `github` directory
- [x] Implement the embeddable dashboard on GitHub -> `Dashboard` tab
- [x] Implement the embeddable dashboard on GitHub -> `Panels` tab
- [x] Implement the embeddable dashboard on GitHub -> `Events` tab

**Comment by Desvelao** [comment]
# Changes

- Implement DataSource on Dashboard and Events tabs
- Prepare to use DataSource on Controls tab. It depends on the changes on https://github.com/wazuh/wazuh-dashboard-plugins/pull/6504
- Replace the usage of NoResults and LoadingSpinner components by the common instead of the local ones
- Fix layout of Dashboard tab when there is a pinned agent

**Comment by Machi3mfl** [comment]
## Panels tabs tasks
 

- [x] Research module to make a plan
- [x]  Apply new search bar on custom-search-bar
- [x]  Change table (alerts table) on drill-down details to data grid
  - [x] Create a new wazuh-data-grid component to reuse the data grid 
- [x]  Use data sources globally on the module
- [ ] Refactor AggTable to use data source (In progress ⏳)

**Comment by Machi3mfl** [comment]
## Add the new data grid component in drilldown details
    

### Before

https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/5359ad03-a6f5-412f-91ba-70fa11b2f0cd
 
### After
      
https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/f69971f2-c406-42e6-9555-f2771a8a373a
