### ISSUE TITLE
[Remove discover] Implement embeddable dashboard on Server Management / Cluster module

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6532]
## Description

We have to implement the embeddable dashboard on **Server Management / Cluster** and deprecate any use of _kibana-integrations_ components.

> [!WARNING]  
> The embeddable panel id must be unique including general and agents visualizations. Otherwise, the visualizations will not refresh when we pin an agent, because they are cached by id

> [!WARNING]  
> https://github.com/wazuh/wazuh-dashboard-plugins/issues/6549 depends on this task

<details>
<summary>
Current Cluster screens
</summary>

**Screen on cluster mode**

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/ab24c227-c58f-4f13-b583-5122ab982e6e)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/dff9daaa-a9e8-4b26-b23a-232d4f9f2085)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/b132fab5-5ac6-45ec-acbf-83ca702ef680)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/09b969d6-c33f-479b-93fb-5fd4e744eacc)

</details>

## Tasks
- [x] Implement the embeddable dashboard on **Server Management / Cluster**
  - [x] Migrate visualizations to embeddable panels
  - [x] Add new searchbar
  - [x] Add conditionality to show the dashboard if there are results.
  - [x] Add loadings
  - [x] Add message that there are no results
  - [x] Keep the "The cluster is disabled" message when in Manager mode
  - [x] Change back button on Overview page (desirable)
  - [x] Change index pattern selection mechanism (Dependence: https://github.com/wazuh/wazuh-dashboard-plugins/issues/6434)
  - [x] Once the previous point have been applied, corroborate filter behavior with respect to `hide alerts`, `allow agents` and filter order (Implicit filters first, then pinned agent, if applicable, and then normal filters).
  - [x] Clean obsolete code
- [x] Check the following:
  - [x] Each visualization, if applicable, must have interaction so that it sets the date range of the searchbar when clicked and  visualizations should refresh when a date range is selected in the search bar.
  - [x] If there are no results, the corresponding message must appear that there are no results and the visualizations should not be rendered.
  - [x] Check that the message "The cluster is disabled" appears when in the cluster is not enabled.
_NOTE: To test this it is necessary to change the cluster configuration in the imposter by setting the `enabled` option to `no` in the `docker/imposter/cluster/cluster_status.json` file and restart the imposter._
  - [x] Check that the message "The cluster is not running" appears when in Manager mode
  - [x] Check filter behavior with respect to `hide alerts` and `allow agents`.
  - [x] Check the link to the list of agents on the Information card for both the name (Agents) and the value.
  - [x] Check that the corresponding information is displayed when you click on "View Overview" and that you can go back from that view.
  - [x] Check that when interacting with the Overview visualization (going to "View Overview") the corresponding filter is added.
  - [x] Check that the list of nodes is shown when you click on both Nodes and the value and that you can go back from that view.
  - [x] Check that fixed filters cannot be deleted or have the onClick functionality

## Source task
- #6477

**Comment by jbiset** [comment]
## Update 20/03/2024

The `Server Management -> Cluster` screen is different from the rest of the dashboards that are being migrated, since the sections of the screen are inserted with Angular through the `management.html` template. Therefore, we are analyzing migrating everything possible to React components without affecting other screens, preparing the context when replacing Angular. This is necessary not only for the replacement of the visualizations, but also for the replacement of the searchbar

Files involved:
- plugins/main/public/services/routes.js
- plugins/main/public/templates/management/management.html
- plugins/main/public/components/index.js
- plugins/main/public/components/management/cluster/cluster-visualization.js
- plugins/main/public/components/management/cluster/cluster-disabled.js

**Comment by jbiset** [comment]
## Update 21/03/2024

Given the need to componentize the Cluster screen with React components. It was decided to modularize all parts of the Cluster screen in the management.html template and reduce it to a minimum. In this way, not only is any use of kibana-integrations components deprecated, but also partial progress is made with the elimination of Angular.

TO DO:
- Reduce everything related to the Cluster screen in management.html to a minimum.
- Migrate Cluster sections to React components
- Implement the embeddable dashboard on Server Management / Cluster

**Comment by jbiset** [comment]
## Update 22/03/2024
Work was done on reducing to a minimum everything related to the Cluster screen in `management.html`.

## MIGRATE CLUSTER MODULE TO REACT COMPONENT

<details>

<summary>
BREADCRUMBS
</summary>

```html
<div
    layout="row"
    layout-align="start center"
    ng-if="mctrl.tab !== 'monitoring' && mctrl.tab !== 'configuration'"
  >
    <!-- Breadcrumbs -->
    <div
      layout="row"
      layout-padding
      ng-if="mctrl.tab === 'groups' && mctrl.currentGroup && mctrl.currentGroup.name"
    >
      <span
        class="wz-text-link cursor-pointer"
        ng-click="mctrl.switchTab('groups', true)"
        >{{ mctrl.tabNames[mctrl.tab] }}</span
      >
      <span> / {{ mctrl.currentGroup.name }} </span>
    </div>
    <!-- End breadcrumbs -->
  </div>
```
It does not affect Cluster as it is only rendered if `mctrl.tab !== 'monitoring' && mctrl.tab !== 'configuration'"`. However, the HOC is added `withGlobalBreadcrumb([{ text: cluster.breadcrumbLabel }])`

</details>

<details>

<summary>
CLUSTER DISABLED MESSAGE BY NOT AUTHORIZED
</summary>


```html
{/* Cluster disabled or not running */}
<div ng-if='!authorized'>
	<react-component
	name='WzEmptyPromptNoPermissions'
	props='{permissions}'
	></react-component>
</div>
```
Replaced with the HOC `withUserAuthorizationPrompt([  { action: 'cluster:status', resource: '*:*:*' },  ])`

</details>


<details>

<summary>
CLUSTER DISABLED MESSAGE BY NOT ENABLED AND RUNNING CLUSTER
</summary>

```html
{/* Cluster disabled or not running */}
<div ng-if='!isClusterEnabled || !isClusterRunning'>
	<react-component
	name='ClusterDisabled'
	props='{enabled: isClusterEnabled, running: isClusterRunning}'
	></react-component>
</div>
```

It is replaced with the corresponding component and the necessary resources of the cluster controller are migrated.

</details>


<details>

<summary>
DISCOVER SEARCH BAR SECTION
</summary>

```html
<!-- Cluster enabled -->
    <div
      ng-show="isClusterEnabled && isClusterRunning && authorized"
      ng-if="mctrl.tab !== 'monitoring'"
      class="monitoring-discover"
    >
      <div ng-show="loading" style="padding: 16px">
        <react-component
          name="EuiProgress"
          props="{size: 'xs', color: 'primary'}"
        ></react-component>
      </div>

      <!-- Discover search bar section -->
      <kbn-dis
        class="hide-filter-control"
        ng-show="!loading && (!showNodes || currentNode)"
      ></kbn-dis>
      <!-- End Discover search bar section -->

      <!-- Loading status section -->
      <div
        class="euiFlexGroup euiFlexGroup--gutterLarge euiFlexGroup--justifyContentSpaceAround euiFlexGroup--directionRow euiFlexGroup--responsive"
      >
        <div
          class="euiFlexItem euiFlexItem--flexGrowZero euiTextAlign euiTextAlign--center"
          ng-show="!loading && !rendered && resultState === 'ready' && (!showNodes || (showNodes && currentNode))"
        >
          <span class="euiLoadingChart euiLoadingChart--large">
            <span class="euiLoadingChart__bar"></span>
            <span class="euiLoadingChart__bar"></span>
            <span class="euiLoadingChart__bar"></span>
            <span class="euiLoadingChart__bar"></span>
          </span>
          <div class="euiSpacer euiSpacer--m"></div>
          <div class="percentage">{{loadingStatus}}</div>
        </div>
      </div>
      <!-- End loading status section -->
    </div>
```

It is replaced by the new searchbar and ng-if is added to the management template so that it is not rendered in the tab monitoring (cluster)

</details>


<details>

<summary>
CLUSTER MAIN SECTION
</summary>


```html
    <!-- main -->
    <div
      class="euiFlexGroup euiFlexGroup--gutterLarge euiFlexGroup--responsive"
      ng-if="!loading && !showConfig && !showNodes && isClusterEnabled && isClusterRunning && authorized"
    >
      <!-- TODO - migrate to a React Component-->

      <!-- Overview card -->
      <div class="euiFlexItem">
        <div class="euiPanel euiPanel--paddingMedium">
          <span class="euiTitle euiTitle--small euiCard__title"
            >Details&nbsp;
            <button
              ng-click="goConfiguration()"
              class="euiButtonEmpty euiButtonEmpty--primary euiButtonEmpty--xSmall"
              type="button"
            >
              <span class="euiButtonEmpty__content"
                ><i class="fa fa-fw fa-pie-chart"></i
                ><span class="euiButtonEmpty__text">View Overview</span>
              </span>
            </button>
          </span>
          <div class="euiSpacer euiSpacer--m"></div>
          <div layout="row" class="wz-padding-top-10">
            <span flex="25">IP address</span>
            <span class="color-grey">{{configuration.nodes[0] || '-'}}</span>
          </div>
          <div layout="row" class="wz-padding-top-10">
            <span flex="25">Running</span>
            <span class="color-grey">{{ status || 'no' }}</span>
          </div>
          <div layout="row" class="wz-padding-top-10">
            <span flex="25">Version</span>
            <span class="color-grey">{{version}}</span>
          </div>
        </div>
      </div>
      <!-- End overview card -->

      <!-- Info card -->
      <div class="euiFlexItem">
        <div class="euiPanel euiPanel--paddingMedium">
          <span class="euiTitle euiTitle--small euiCard__title"
            >Information</span
          >
          <div class="euiSpacer euiSpacer--m"></div>
          <!-- Nodes -->
          <div
            layout="row"
            class="wz-padding-top-10 cursor-pointer"
            ng-click="goNodes()"
          >
            <span
              flex="25"
              class="wz-text-link"
              tooltip="Click to open the list of nodes"
              tooltip-placement="left"
              >Nodes</span
            >
            <span
              class="wz-text-link"
              tooltip="Click to open the list of nodes"
              tooltip-placement="right"
              >{{nodesCount}}</span
            >
          </div>
          <!-- Agents -->
          <div
            layout="row"
            class="wz-padding-top-10 cursor-pointer"
            ng-click="goAgents()"
          >
            <span
              flex="25"
              class="wz-text-link"
              tooltip="Click to open the list of agents"
              tooltip-placement="left"
              >Agents</span
            >
            <span
              class="wz-text-link"
              tooltip="Click to open the list of agents"
              tooltip-placement="right"
              >{{agentsCount}}</span
            >
          </div>
        </div>
      </div>
      <!-- End info card -->
    </div>
    <!-- end main -->
```

The elements are migrated to the new ClusterOverview class component and the necessary resources of the Cluster controller

</details>

**Comment by jbiset** [comment]
## Update 26/03/2024

- Migrated Timelions visualizations to embeddable panels
- Replace html tags from template `management.html` with OpenSearch UI components
- The structure is adjusted so that the order `searchbar` -> `overview-cards` -> `Timelions visualizations` is respected
- Add loadings
- Add message that there are no results

TO CONTINUE:

- Check the definition of Alerts by node summary so that it shows all nodes
- Complete `View Overview` rendering functionality

## Current screen

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/ce2b0ebb-9c36-4993-bc55-27dda0a152d5)

**Comment by jbiset** [comment]
## Update 27/03/2024

- View Overview rendering functionality is completed
- Fixed definition of Timelions visualizations
- Changed back button on Overview page
- Added cluster nodes table rendering
- Removed obsolete code from:
  - plugins/main/public/templates/management/management.html
  - plugins/main/public/controllers/management/index.js
  - plugins/main/public/components/index.js
- Final aesthetic changes are made


## Current Server Management -> Cluster
[Evidence.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/b46d518c-decb-4288-a691-0246fe31c097)


_The task is blocked until the dependencies are resolved_

**Comment by jbiset** [comment]
## Update 08/04/2024

- Changed index pattern selection mechanism.
- Corroborated filter behavior with respect to hide alerts, allow agents and filter order.
- Changed DiscoverNoResults and Loading-Spinner common components.

**Comment by jbiset** [comment]
## Update 16/04/2024

- Fixed `configuration_cards` itemsList
- The code is improved according to suggestions to the PR
- Unnecessary code is removed
