### ISSUE TITLE
Refine vulnerabilities dashboard

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6533]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 05 | - |

## Description
As part of the feedback cycle, we decided to make the following changes to improve the Vulnerabilities dashboard.

Epic:
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/5763

## Tasks

- [x] The _severity_ KPIs must be placed in the first row of the dashboard
- [x] The _filter tables_ must be placed in the second row of the dashboard
- [x] The _filter tables_ order must be: **_Top 5 vulnerabilities_**, **_Top 5 OS_**, **_Top 5 agents_**, **_Top 5 packages_**
- [x] The **_Top 5 OS_**, **_Top 5 agents_** tables must be wider than the **_Top 5 vulnerabilities_**, **_Top 5 packages_** tables
- [x] We have to remove the word alerts and hyphens from the KPIs
- [x] We must change the `@timestamp` field used in the **_Accumulation of the most detected vulnerabilities_** visualization for the new field `vulnerability.published_at`
 - Related pull request: https://github.com/wazuh/wazuh/pull/22611

![screencapture-vulnerability-detection-2024-03-19-18_03_00](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/bc99a10b-569e-49b3-9e2b-7a81763672cd)
