### ISSUE TITLE
Support new stage RC 2 for 4.7.4 in wazuh-dashboard-plugins repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard-plugins#6619]
## Description

This issue attempts to support a new stage RC 2 for 4.7.4 in the wazuh-dashboard-plugins repository.

## Tasks

- [x] Ensure changelog is updated for 4.7.4 (if applicable).
- [x] Bump revision for branch 4.7.4 on wazuh-dashboard-plugins repository. https://github.com/wazuh/wazuh-dashboard-plugins/pull/6620
- [x] Create tag v4.7.4-2.8.0-rc2 from branch 4.7.4 on wazuh-dashboard-plugins repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard-plugins/releases/tag/v4.7.4-2.8.0-rc2.
