### ISSUE TITLE
Refine dashboards visualizations

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6628]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 08 | - |

# Description
There are some visualizations that aren't segregated by any field and only show a **_Count_** label. We need to identify these visualizations and hide the label. More over, in the PCI DSS dashboard the visualizations **"Top 10 PCI DSS requirements"** and **"Top requirements over time"** are very similar. We should remove the **"Top requirements over time"** visualization and aggregate the **"Top 10 PCI DSS requirements"** values by `rule.pci_dss`

**Screenshots**

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/92e1a814-c9d5-45ba-902c-2073533fcd46)

## Tasks

- [x] Remove the **_Count_** labels in visualizations.
- [x] Remove the **"Top requirements over time"** visualization
- [x] Aggregate the **"Top 10 PCI DSS requirements"** values by `rule.pci_dss`
