### ISSUE TITLE
Refine filter mechanism

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6672]
| Wazuh | Rev  |
|-------|------|
| 4.9.0 | 00 | 

# Description
After testing all main features integrated we detected some odd behaviors that need fixing.

## Tasks
- [x] Server management / Cluster applies any previous pinned agent and it shouldn't https://github.com/wazuh/wazuh-dashboard-plugins/pull/6681
- [x] Server management / Statistics applies any previous pinned agent and it shouldn't https://github.com/wazuh/wazuh-dashboard-plugins/pull/6682
- [x] When changing the API selected to a Wazuh server with cluster mode disabled the filter value is "disabled" https://github.com/wazuh/wazuh-dashboard-plugins/pull/6675
- [x] In the Vulnerabilities module, when we change the index pattern the view doesn't render any https://github.com/wazuh/wazuh-dashboard-plugins/pull/6674
- [x] Remove Wazuh server link (**_000_**) from alerts tables https://github.com/wazuh/wazuh-dashboard-plugins/pull/6679
- [x] Add link to agent id and name in discover table (in progress) https://github.com/wazuh/wazuh-dashboard-plugins/pull/6677
- [x] Check remove filter icon disappears when you unpin an agent https://github.com/wazuh/wazuh-dashboard-plugins/pull/6685
- [x] Check the order in which filters are rendered https://github.com/wazuh/wazuh-dashboard-plugins/pull/6684
- [x] When navigating to the home page if there is a pinned agent you should keep it. https://github.com/wazuh/wazuh-dashboard-plugins/pull/6686
- [x] Check the flyout of the discover table. https://github.com/wazuh/wazuh-dashboard-plugins/pull/6691
- [x] Fix modules redirections with predefined filters via URL  https://github.com/wazuh/wazuh-dashboard-plugins/pull/6712

**Comment by Machi3mfl** [comment]
## In the Vulnerabilities module, when we change the index pattern the view doesn't render any visualization


### Before

https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/ed472a58-a6e7-4da9-b577-4074572a0e14

### This error 
<img width="594" alt="Screenshot 2024-05-15 at 11 42 51" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/6dd6458b-992e-4598-874d-b2062a334865">



### After

https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/b7756ab9-a9d6-479a-9387-7ffd0ebff7a7

**Comment by Machi3mfl** [comment]
## Fix modules redirections with predefined filters via URL

### Tasks

- Create a mechanism to make a redirect with filters by default.
- Add to the current solution the possibility to add filters that will be applied when entering the module.

### Current solution 

1. Using the getUrlForApp to get the redirect href

```tsx

<EuiButtonEmpty
                iconType='popout'
                aria-label='popout'
                href={getCore().application.getUrlForApp(threatHunting.id, {
                  path: `#/overview/?tab=general&tabView=panels&addRuleFilter=1001`
                })}
                target='blank'
              >
                View alerts of this Rule
              </EuiButtonEmpty>
```
2. In `plugins/wazuh/public/services/common-data.js`, globally check the URL query, search  the addRuleFilter and add directly to the filter manager the filter

```tsx
const regex = new RegExp('addRuleFilter=' + '[^&]*');
      const match = this.$window.location.href.match(regex);
      if (match && match[0]) {
        const id = match[0].split('=')[1];
        let filter = filterHandler.ruleIdQuery(id);
        filter.$state.isImplicit = false;
        filters.push(filter);
        this.$window.location.href = this.$window.location.href.replace(
          regex,
          '',
        );
      }

```

## Disadvantages

- Not scalable, for every filter that we want to add we must add a condition to check the param received, like for example, the `addRuleFilter` param.
- To many responsibilities, the redirect touches the filter manager directly


# Possible solutions

- Encapsulate the getCore().application.getUrlForApp method and create a function that creates the redirect URL with all the necessary params like:
  - panel
  - tab
  - predefined filters (one or more)
  
  For instance: 
  
```ts
     // redirect manager or something 
     
    redirector.redirectToApp({
      tab: 'general',
      tabView: 'panels',
     applicationId: 'threat-hunting',
    filters: [{ key: 'rule.id', value: '1001' }]
    })

```

Then this service construct the URL with the params like:
 - ruleId=1001 or inner a_ filters query

### Problem

When the URL is refreshed using enter or F5 the a_ content is cleaned
  
- Use the same solution, adding custom query params manually and evaluate this query params in the data-source-pattern-filter-manager and add the filters

For instance: 

```ts

getCore().application.getUrlForApp(threatHunting.id, {
                  path: `#/overview/?tab=general&tabView=panels&filters='ruleId=1001&ruleMitreId=T100`
                })
```

Then, when the data source is loaded the data source filter manager gets the query params, creates the filters and add on it.

**Comment by lucianogorza** [comment]
## Proposals to display implicit filters in the search bar

### Option 1: Show all implicit filters` without the close button`

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/d5d9fe0b-1e85-4099-810d-81187ca14ff2)

### Option 1: Show all implicit filters `without the close button and with another background color`

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/768d1fb8-ae42-466e-8f62-f6c7d07fb732)
