### ISSUE TITLE
Minor style issues

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6692]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | 00 | Chrome, Firefox, Safari, etc |

# Description
The goal of this issue is to fix all minor style issues that we detected in the early stages of Wazuh dashboard 4.9.0. 

### Threat Hunting alerts bottom table doesn't have margin
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/ec8de07d-c43e-44ce-884d-c7be83753931)

### Standardize search bar padding in Events tabs
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/7e49e338-808c-4fe0-bf99-cb6929ff4d4e)

### Standardize search bar padding in Vulnerability Detection Inventory tab
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/4d99dd52-eb17-4727-932e-335b5e2eff39)

### Standardize search bar padding in Mitre Att@ct Framework tab
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/3d8c09f6-f761-4834-8594-ef5b709d84b8)

### Standardize search bar padding in Controls tab from PCI DSS, GDPR, HIPAA, NITS and TSC
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/d9414f7e-ec72-4984-97df-6a684bc60234)

## Tasks
- [x] Threat Hunting alerts bottom table doesn't have margin.
- [x] Standardize search bar padding in Events tabs.
- [x] Standardize search bar padding in Vulnerability Detection Inventory tab.
- [x] Standardize search bar padding in Mitre Att@ct Framework tab.
- [x] Standardize search bar padding in Controls tab from PCI DSS, GDPR, HIPAA, NITS and TSC.
- [x] Standardize margins and paddings in Dashboard, Events, Inventory and Control tabs from all modules.

**Comment by lucianogorza** [comment]
# Analysis

Going through the application modules and the tabs of each module, we find different layouts, which present different spacings between the components.

For example, in the `Threat Hunting` module, the space between components is 8px in the `Dashboard` tab, while it is 24px in the `Events` tab.

#### Threat Hunting -> Dashboard tab
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/a566a29a-f9eb-4dd0-8e2b-9d0c9b408f08)

 #### Threat Hunting -> Events tab
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/1a2bed73-e74f-4797-80b3-898ee8cc3dae)

**Comment by lucianogorza** [comment]
## Events tab with the same spaces as Dashboard tab

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/cee198f1-f222-4abc-83aa-f9cdc6683ba6)

**Comment by lucianogorza** [comment]
## Mitre Att&ct Framewrok tab
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/3794148e-4270-4b54-acd7-bff13bc3fc5d)

**Comment by lucianogorza** [comment]
## Vulnerability Detection Inventory Tab

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/a86ca060-ff26-4260-b270-05ee35d023ce)

**Comment by lucianogorza** [comment]
## Controls tab from PCI DSS, GDPR, HIPAA, NITS and TSC

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/da0e9c12-6c12-451d-a581-5e368e86a185)
