### ISSUE TITLE
Warnings and errors in console

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6693]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | 00 | - |

# Description
The app has several warnings and some errors printed in the browser console. We need to address them.

## Tasks

- [x] Failed prop type: Invalid prop `children` of type `array` supplied to `I18nProvider`, expected a single ReactElement 
- https://github.com/wazuh/wazuh-dashboard-plugins/pull/6698

<details>
<summary>Evidence</summary>
<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/fa4de7e1-d23d-4a15-b3c7-338b044e4fcb">

</details>

- [ ] Can't perform a React state update on an unmounted component. https://github.com/wazuh/wazuh-dashboard-plugins/pull/6704
<details>
<summary>Evidence</summary>

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/d1a45e7c-e7a7-44d2-864c-3bc968116f28">

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/66c99155-dbf6-4f84-a150-bf5a04ec74af)

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/96680864-68e6-48c5-a464-4a1f9bd9299b">

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/31d81403-e6b2-420e-bcf2-91c5f9b4c295">

</details>

- [x] componentWillReceiveProps has been renamed, and is not recommended for use. (It comes from the embeddables plugin)
<details>
<summary>Evidence</summary>

<img width="1507" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/430e8db0-e503-47e9-8e1d-6d802fc01c90">

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/76a51306-2950-4d72-8db4-28f764058b02)

</details>

- [x] Failed prop type: EuiSuggestItem: prop type `type.iconType` is invalid https://github.com/wazuh/wazuh-dashboard-plugins/pull/6714
<details>
<summary>Evidence</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/db401fd0-8772-436d-a8b8-c5f8e2d23fe2)
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/5c81f37f-7614-4ca9-92be-b2e359fe770b)

</details>

- [x] Warning: validateDOMNesting(...): `<div>` cannot appear as a descendant of `<p>`.
- https://github.com/wazuh/wazuh-dashboard-plugins/pull/6701
<details>
<summary>Evidence</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/64f03c24-8652-4b30-9c63-9b38f8265130)

</details>

- [ ] EuiButtonIcon requires aria-label or aria-labelledby to be specified because icon-only buttons are screen-reader-inaccessible without them. 

<details>
<summary>Evidence</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/d43970d8-d45e-429f-826c-ab33f3a9329c)

</details>

- [ ] Failed prop type: The prop `onChange` is marked as required in `EuiSwitch`, but its value is `undefined`. @chantal-kelm in progress

<details>
<summary>Evidence</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/271d759b-5402-4907-b487-9a672d5f49ff)
</details>

- [x] Failed prop type: Invalid props supplied to `EuiInMemoryTable`
- https://github.com/wazuh/wazuh-dashboard-plugins/pull/6707
<details>
<summary>Evidence</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/b9554402-6384-4342-aca3-36e39e3f71fd)
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/fee3013a-581f-45d0-8c46-3afca249199c)

</details>

- [ ] Error: Embeddable has been destroyed (in progress @yenienserrano )

Steps for reproduce:

- Go to Threat intelligence > Threat Hunting and change between tabs quickly 

<details>
<summary>Evidence</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/6fef52c6-0de0-443d-9764-b391b49ca0f8)

</details>

- [x] Each child in a list should have a unique "key" prop. https://github.com/wazuh/wazuh-dashboard-plugins/pull/6715

<details>
<summary>Evidence</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/20498c92-a221-472b-a4b0-32280d806fad)
</details>

- [ ]  Failed prop type: Invalid prop `value` supplied to `EuiSelect`, expected one of type [string, number] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6722

<details>
<summary>Evidence</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/47031888-68e8-49ac-961e-184a622a00b9")
</details>

- [x]  Failed prop type: Invalid prop `children` of type `array` supplied to `PseudoLocaleWrapper`, expected a single ReactElement.  https://github.com/wazuh/wazuh-dashboard-plugins/pull/6723 

<details>
<summary>Evidence</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/b2aacba6-a73c-40be-8695-d931f65482a6">")
</details>

- [x]  React does not recognize the `isClearable` prop on a DOM element.  https://github.com/wazuh/wazuh-dashboard-plugins/pull/6725

<details>
<summary>Evidence</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/af0e4d98-c7e7-411c-9e45-8b1b4c67d56e">")
</details>

- [x]  React does not recognize the `isDisabled` prop on a DOM element. https://github.com/wazuh/wazuh-dashboard-plugins/pull/6725

<details>
<summary>Evidence</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/003dc7b2-7c27-4cc9-87c6-861790a81e54">")
</details>

- [x]  React does not recognize the `selectedOptions` prop on a DOM element. https://github.com/wazuh/wazuh-dashboard-plugins/pull/6725

<details>
<summary>Evidence</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/bff9f2c5-013f-42b6-9637-e9184049366b">")
</details>

**Comment by yenienserrano** [comment]
> componentWillReceiveProps has been renamed, and is not recommended for use.

I think it is better to wait for a fix from opensearch to avoid future conflicts in future updates.

**Comment by yenienserrano** [comment]
When rendered correctly in the events view it loads 1 single visualisation accordingly.

<img width="1508" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/84a5f13e-0857-4899-b0ce-966ff542132a">
<img width="789" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/df598e58-d603-47bd-a81b-8b6ddd24503a">

But when a quick tab change is made, the dashboards of the dashboard are sent to events and cause it to break.

<img width="1507" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/626c319e-80cc-414e-85ef-525be7d542e9">
<img width="1509" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/a0e33264-64fc-4f43-ad40-56bd65b0f05e">

**Comment by chantal-kelm** [comment]
It was decided to postpone this task in order to build a common solution for all components. This will be done in this [issue](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6738).


- [ ] Can't perform a React state update on an unmounted component. https://github.com/wazuh/wazuh-dashboard-plugins/pull/6704
<details>
<summary>Evidence</summary>

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/d1a45e7c-e7a7-44d2-864c-3bc968116f28">

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/66c99155-dbf6-4f84-a150-bf5a04ec74af)

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/96680864-68e6-48c5-a464-4a1f9bd9299b">

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/31d81403-e6b2-420e-bcf2-91c5f9b4c295">

</details>
