### ISSUE TITLE
Create Wazuh Searchbar component

### ISSUE THREAD

**Issue by lucianogorza** [wazuh/wazuh-dashboard-plugins#6711]
## Description
Currently, we are using the native OpenSearch search bar, and because we need to extend its functions, we are altering its functionality and appearance.

For example, there are filters that are fixed and should not be removable by the user, such as the `manager/cluster` or the `pinned agent`. To prevent users from removing these filters, we are modifying the displayed component to hide the remove button. However, in some specific cases, our modification is overwritten, resulting in unexpected behavior.

To address this and provide a more robust solution, we aim to **create a new Wazuh Searchbar** component that internally handles both fixed and user-added filters and displays them correctly.

## Tasks
- [x] Create `WzSearchbar` component
- [x] Modify `useSearchBar` hook to return fixed and user filters
- [x] Implement new searchbar:
  - [x] `WzDiscover`
  - [x] `Threat Hunting`
  - [x] `Malware Detection`
  - [x] `FIM`
  - [x] `Mitre Att&ct`
  - [x] `Vulnerability Detection`
  - [x] `Virus Total`
  - [x] `PCI DSS`
  - [x] `GDPR`
  - [x] `HIPAA`
  - [x] `NIST`
  - [x] `TSC`
  - [x] `Docker`
  - [x] `AWS`
  - [x] `GC`
  - [x] `GH`
  - [x] `Office 365`
  - [x] Management Cluster Dashboard
- [x] Modify `CustomSearchBar`
- [x] Validate `CustomSearchBar`
  - [x] GitHub Panel
  - [x] Office 365 Panel

**Comment by lucianogorza** [comment]
# New search bar implementation

## WzDiscover

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/11c912a7-a780-4e76-8a97-c8da4a28a746)

##  Threat Hunting

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/32354996-c0be-479f-8300-9e9a8d77c387)

## Malware Detection

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/f7c160fb-5363-416f-ae96-53d6e70cfbe9)

## FIM

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/903c4c5e-6da9-4e60-9c71-9f7f74900453)

## Virus Total

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/18e29909-eb90-4e2a-a88c-853b37e9d5db)

**Comment by lucianogorza** [comment]
## Modify CustomSearchBar

### GitHub Panel

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/00543708-c165-4118-a877-163a18cef1be)

### Office 365 Panel

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/4b9c8275-d255-4750-913d-27748067ee1b)
