### ISSUE TITLE
Warning: Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by chantal-kelm** [wazuh/wazuh-dashboard-plugins#6738]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | 00 | - |

## Description

The application has a warning that is repeated many times throughout the application. We need to fix it.

**Can't perform a React state update on an unmounted component.**
<details>
<summary>Evidence</summary>

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/d1a45e7c-e7a7-44d2-864c-3bc968116f28">

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/66c99155-dbf6-4f84-a150-bf5a04ec74af)

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/96680864-68e6-48c5-a464-4a1f9bd9299b">

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/31d81403-e6b2-420e-bcf2-91c5f9b4c295">

</details>

## Tasks

- [ ] Create a hook to fix the warning.
- [ ] Use the hook in all functional components of the application.
- [ ] Define the best way to solve the warning in class components

## Additional information
Add here any additional information relevant to the issue or that will help to close it: chunks of code, logs, additional error messages, related issues and so on.

**Comment by chantal-kelm** [comment]
After some research on libraries that provide us with a solution, I have created a hook to solve the warning Can't perform a React state update on an unmounted component.
This hook will allow us to implement a global solution in the application to solve the warning.
