### ISSUE TITLE
Refactor state navigation to routing navigation

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6774]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | 00 | Chrome, Firefox, Safari, etc |

# Description

We need to identify which sections and view navigate using the internal components state, so we can refactor this behavior to navigate using the URL path. This will enhance the user experience and allow the user to store the navigation in the browser history.

## Tasks

- [ ] Make a list of these views which navigate using an internal component state

**Comment by JuanGarriuz** [comment]
### Update 17/06

<details><summary>Sample Data</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/b5a0507e-e6ea-4d44-b04e-607fd5a9edc7)
- plugins/main/public/components/add-modules-data/sample-data.tsx

</details>

**Comment by JuanGarriuz** [comment]
## Update 18/06

### Threat intelligence

- [ ] MITRE ATT&CK > Intelligence > Flyouts 
- [ ] MITRE ATT&CK > Framework  > Flyouts

### Security operations

- [ ] PCI DSS > Controls > Requirements > Flyouts 
- [ ] GDPR > Controls > Requirements > Flyouts 
- [ ] HIPAA > Controls > Requirements > Flyouts 
- [ ] NIST 800-53 > Controls > Requirements > Flyouts 
- [ ] TSC > Controls > Requirements > Flyouts 

### Cloud security

- [ ] GitHub > Panels 
- [ ] Office > Panels 

### Server management

#### Endpoint Groups

- [ ] Endpoint Groups > View details
- [ ] Endpoint Groups > Edit configuration
- [ ] Endpoint Groups > `$Group`
- [ ] Endpoint Groups > `$Group` > Agents > Manage Agents
- [ ] Endpoint Groups > `$Group` > Agents > Go to Agent
- [ ] Endpoint Groups > `$Group` > Files > Edit group configuration
- [ ] Endpoint Groups > `$Group` > Files > See file content

#### Rules

- [ ] Rule > Manage rules files
- [ ] Rule > Add new rules file
- [ ] Rule > '$rule' > Flyout
- [ ] Rule > '$rule' > File

#### Decoders

- [ ] Decoders> Manage decoders files
- [ ] Decoders> Add new decoders file
- [ ] Decoders> '$decoder' > Flyout
- [ ] Decoders> '$decoder' > File
