### ISSUE TITLE
Support new stage Alpha 1 for 4.9.0 in wazuh-dashboard-plugins repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-dashboard-plugins#6786]
## Description

This issue attempts to support a new stage Alpha 1 for 4.9.0 in the wazuh-dashboard-plugins repository.

## Tasks

- [x] Ensure changelog is updated for 4.9.0 (if applicable).
- [x] Bump revision for branch 4.9.0 on wazuh-dashboard-plugins repository.
  - https://github.com/wazuh/wazuh-dashboard-plugins/pull/6787
- [x] Create tag v4.9.0-alpha1 from branch 4.9.0 on wazuh-dashboard-plugins repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard-plugins/releases/tag/v4.9.0-alpha1.

**Comment by Desvelao** [comment]
LGTM!
