### ISSUE TITLE
Support new stage RC 1 for 4.8.1 in wazuh-dashboard-plugins repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard-plugins#6808]
## Description

This issue attempts to support a new stage RC 1 for 4.8.1 in the wazuh-dashboard-plugins repository.

## Tasks

- [x] Ensure changelog is updated for 4.8.1 (if applicable).
- [x] Bump revision for branch 4.8.1 on wazuh-dashboard-plugins repository. https://github.com/wazuh/wazuh-dashboard-plugins/pull/6809
- [x] Create tag v4.8.1-rc1 from branch 4.8.1 on wazuh-dashboard-plugins repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard-plugins/releases/tag/v4.8.1-2.10.0-rc1.
