### ISSUE TITLE
Remove redirection to agent 000 from security operations modules

### ISSUE THREAD

**Issue by yenienserrano** [wazuh/wazuh-dashboard-plugins#6844]
**Description**

Remove redirection to agent 000 from the flyouts of the Control tab of the security operations modules.

**Tasks**

- [x] Remove redirection to agent 000
- [x] Fix render requirement column values 
- [x] Unify rendering of flyout columns

**Steps to reproduce**
1. Navigate to 'Security operations > some module > Control > some requirement with alerts of agent 000'
2. It must not be a link agent 000

**Expected Result**
1. 
<img width="1283" alt="image" src="https://github.com/user-attachments/assets/90b73171-a41b-4273-9fc3-f911ac9c480a">

**Actual Result**
1. 
<img width="1288" alt="image" src="https://github.com/user-attachments/assets/d7999073-4977-4245-a6ec-c69e67d6909e">
