### ISSUE TITLE
Support new stage RC 1 for 4.8.2 in wazuh-dashboard-plugins repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard-plugins#6914]
## Description

This issue attempts to support a new stage RC 1 for 4.8.2 in the wazuh-dashboard-plugins repository.

## Tasks

- [x] Ensure changelog is updated for 4.8.2 (if applicable).
- [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6915
- [x] Create tag v4.8.2-rc1 from branch 4.8.2 on wazuh-dashboard-plugins repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard-plugins/releases/tag/v4.8.2-2.10.0-rc1.

**Comment by yenienserrano** [comment]
LGTM
