### ISSUE TITLE
Post release tasks for 4.8.2

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard-plugins#6925]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.8.2.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.8.2-into-4.9.0`.

## Tasks

- [x] Merge branch `4.8.2` into branch `4.9.0`. https://github.com/wazuh/wazuh-dashboard-plugins/pull/6928
- [x] Merge branch `4.9.0` into branch `4.9.1`. https://github.com/wazuh/wazuh-dashboard-plugins/pull/6929
- [x] Merge branch `4.9.1` into branch `4.10.0`. https://github.com/wazuh/wazuh-dashboard-plugins/pull/6930
- [x] Merge branch `4.10.0` into branch `master`. https://github.com/wazuh/wazuh-dashboard-plugins/pull/6931
- [x] Publish GitHub release as latest. https://github.com/wazuh/wazuh-dashboard-plugins/releases/tag/v4.8.2-2.10.0
- [x] Delete all stage pre-releases for 4.8.2 (https://github.com/wazuh/wazuh-dashboard-plugins/releases).
- [x] Delete all stage tags for v4.8.2. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.8.2-rc1, 4.8.2-alpha1, etc.
