### ISSUE TITLE
Remove many loading spinners in some views

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6946]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | - | Chrome, Firefox, Safari, etc |

**Description**
Currently, the search bar has a loading spinner which makes some views have several loading spinners and also displaces the search bar. We should avoid this by removing the loading of find a way to have a single loading in the page.

**Steps to reproduce**
1. Navigate to MITRE ATT&CK -> Framework
2. See the loading spinners 

![Peek 2024-08-26 16-30](https://github.com/user-attachments/assets/67bd2808-6c42-4cc5-9354-2fb8dca32860)

**Comment by asteriscos** [comment]
One possibility would be to use a progress bar and match the height of the loading component to the search bar so the components aren't displaced when it finishes loading.



![Image](https://github.com/user-attachments/assets/71d14e73-829c-47ae-bf4f-468adb8965d2)

**Comment by guidomodarelli** [comment]
# Tasks

- [x] Create a new loading component
- [x] Apply new loading in `plugins/wazuh/public/components/overview/mitre/framework/mitre.tsx`

<details>

### Before

https://github.com/user-attachments/assets/04c0b337-709b-422d-8a21-bc38b051189c

https://github.com/user-attachments/assets/2f04bb50-917f-4d78-9311-a94be2d20220

### After

https://github.com/user-attachments/assets/a9f77805-6667-468e-8090-91ea907d90ff

https://github.com/user-attachments/assets/9e9b7204-e36b-4bab-8db5-a6605bcc55e0

</details>

- [ ] Apply new loading in `plugins/wazuh/public/components/overview/mitre/dashboard/dashboard.tsx`

<details>

### Before

https://github.com/user-attachments/assets/5cd7b5d6-7b04-4b98-b7dd-7230e55413eb

https://github.com/user-attachments/assets/e8cd90d1-7bbd-4cda-a8a1-d3f35766a335

### After

https://github.com/user-attachments/assets/75a6c908-6f3a-4fad-a22f-5dfef15df96a

https://github.com/user-attachments/assets/0f501506-39c0-4848-9188-73758147f366


</details>
