### ISSUE TITLE
Extract common services from main plugin

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6959]
## Description
Historically the main Wazuh dashboard plugin contains many common services needed for the different modules to work. We are in the process of segregating the different modules into decoupled plugins, so we need a common service provider for all of them. Therefore we need to evaluate which services are common to the modules and extract them from main plugin into a common service provider plugin.

#### Objective 
- https://github.com/wazuh/wazuh/issues/22887

## Tasks
The steps that have to be completed in order to close the issue.

- [x] Identify and make a list of the services to extract https://github.com/wazuh/wazuh-dashboard-plugins/issues/6959#issuecomment-2345873062
- [ ] Extract the services into a common provider
  - [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/7000
  - [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/7026
  - [ ] https://github.com/wazuh/wazuh-dashboard-plugins/pull/7037
- [ ] Implement the common provider in each module

## Functional requirements
- We must user the mechanisms provided in the life cycle of OpenSearch plugins to expose them, so other plugins can make use of them.

**Comment by Desvelao** [comment]
# Frontend - serverSecurity

The `serverSecurity` service manages the security related to the Wazuh server.

- Permissions

Expose hooks, HOCs and UI elements related to the user permissions.

**Comment by Desvelao** [comment]
# Frontend - state

The `state` service manages the shared state of the Wazuh plugins and it is a HUB of state containers. Features:

- Extensible
- Register state containers
- Ability to get, set, remove data and subscribe to changes of state containers

The state containers provides a mechanism to manage a specific state. For example, some data is stored in cookies, others could be managed in-memory, local storage, session storage.

Others plugins can register new state containers.

The service creates hooks and HOCs that are exposed through the plugin lifecycle.
