### ISSUE TITLE
Post release tasks for 4.9.0

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-dashboard-plugins#6967]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.9.0.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.9.0-into-4.9.1`.

## Tasks

- [x] Merge branch `4.9.0` into branch `4.9.1`. https://github.com/wazuh/wazuh-dashboard-plugins/pull/6973
- [x] Merge branch `4.9.1` into branch `4.10.0`. https://github.com/wazuh/wazuh-dashboard-plugins/pull/6974
- [ ] Merge branch `4.10.0` into branch `master`. 
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.9.0 (https://github.com/wazuh/wazuh-dashboard-plugins/releases).
- [x] Delete all stage tags for v4.9.0. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.9.0-rc1, 4.9.0-alpha1, etc.
- [ ] Update [Compatibility Matrix](https://github.com/wazuh/wazuh-dashboard-plugins/wiki/Compatibility) in the repository wiki.
