### ISSUE TITLE
Add vulnerabilities card to Agent details page

### ISSUE THREAD

**Issue by Machi3mfl** [wazuh/wazuh-dashboard-plugins#7058]
## Description

Redesign the agent details page and add the vulnerabilities KPIs to the agent details page.

![image](https://github.com/user-attachments/assets/4ea82958-45a0-43d6-9004-2d8427cabbde)

Parent issue #7051

## Tasks 

- [x] Reorder agent details page cards
- [x] Add vulnerabilities card
- [x] Add vulnerabilities KPIs
- [x] Add Top packages table

**Comment by Machi3mfl** [comment]
## Update 2024/10/07

<img width="744" alt="Screenshot 2024-10-07 at 9 36 38 PM" src="https://github.com/user-attachments/assets/251a07fa-59a8-47cb-a701-d43e3949b534">

https://github.com/user-attachments/assets/5c70fbe7-67c4-4e96-9e6a-c83496cf7735

**Comment by Machi3mfl** [comment]
## Update 2024/10/09


https://github.com/user-attachments/assets/da56c565-c904-442c-8189-8f54390281c6
