### ISSUE TITLE
Post release tasks for 4.9.1

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-dashboard-plugins#7104]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.9.1.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.9.1-into-4.10.0`.

## Tasks

- [ ] Merge branch `4.9.1` into branch `4.10.0`.
- [ ] Merge branch `4.10.0` into branch `4.10.1`.
- [ ] Merge branch `4.10.1` into branch `4.10.2`.
- [ ] Publish GitHub release as latest.
- [ ] Delete all stage pre-releases for 4.9.1 (https://github.com/wazuh/wazuh-dashboard-plugins/releases).
- [ ] Delete all stage tags for v4.9.1. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.9.1-rc1, 4.9.1-alpha1, etc.
- [ ] Update [Compatibility Matrix](https://github.com/wazuh/wazuh-dashboard-plugins/wiki/Compatibility) in the repository wiki.

**Comment by guidomodarelli** [comment]
LGTM
