### ISSUE TITLE
Support new stage RC 1 for 4.9.2 in wazuh-dashboard-plugins repository

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh-dashboard-plugins#7132]
## Description

This issue attempts to support a new stage RC 1 for 4.9.2 in the wazuh-dashboard-plugins repository.

## Tasks

- [x] Delete previous Alpha 2 release: https://github.com/wazuh/wazuh-dashboard-plugins/releases/tag/v4.10.0-alpha2.
- [x] Delete previous v4.10.0-alpha2 tag.
- [x] Ensure changelog is updated for 4.9.2 (if applicable).
- [x] Bump revision for branch 4.9.2 on wazuh-dashboard-plugins repository. https://github.com/wazuh/wazuh-dashboard-plugins/pull/7134
- [x] Create tag v4.9.2-rc1 from branch 4.9.2 on wazuh-dashboard-plugins repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard-plugins/releases/tag/v4.9.2-rc1.
