### ISSUE TITLE
Improve agent details page

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#7193]
# Description
We want to refine some aspects of the Agent dashboard to enhance the use experience. To achieve this we will do the following tasks.

## Tasks

- [x] Adjust height of events count evolution visualization

  ![image](https://github.com/user-attachments/assets/7385c689-def8-4635-bba2-1d70e1f43ffa)
  
<hr/>

- [x] Apply the same padding as the other tables to the Top 5 Packages table.

  ![image](https://github.com/user-attachments/assets/ca915379-5eb8-4d89-82d9-5354aebb0efc)
  
<hr/>

- [x] Reduce the width of small fields

  ![image](https://github.com/user-attachments/assets/6f06222d-305f-473b-88cf-e5676a8f75c4)
  
<hr/>

- [x] Replace the position of Malware detection for Vulnerability detection in the agent navigation menu.

  ![image](https://github.com/user-attachments/assets/10a50bdb-8ef6-451f-a6f7-e14ef434537d)
  
<hr/>

- [x] Align Vulnerability detection KPI's to the left.

  ![image](https://github.com/user-attachments/assets/c6f19eb7-05ec-4281-8bbb-3306d6d8820c)
